<?php
/**
 * Compliance Data Provider
 *
 * This class provides embedded compliance data for ISO 27001, SOC 2, and HIPAA
 * frameworks. The data is sourced from Statement of Applicability markdown files
 * and embedded here to ensure it's available in deployed plugin packages.
 *
 * DO NOT EDIT THIS FILE MANUALLY.
 * This file is auto-generated by bin/generate-compliance-data.php
 * Run `php bin/generate-compliance-data.php` to regenerate.
 *
 * @package WP_MCP_AI
 * @since 1.5.0
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

if ( ! class_exists( 'WP_MCP_AI_Compliance_Data' ) ) {
	/**
	 * Provides embedded compliance framework data.
	 *
	 * @since 1.5.0
	 */
	class WP_MCP_AI_Compliance_Data {
		/**
		 * Get ISO 27001:2022 controls.
		 *
		 * Returns all 93 controls from Annex A with their implementation status,
		 * applicability, justification, and descriptions.
		 *
		 * @return array Array of controls with id, name, status, status_key, applicable, justification, and description.
		 */
		public static function get_iso27001_controls() {
			return array(
				0  =>
				array(
					'id'            => 'A.5.1',
					'name'          => 'Policies for Information Security',
					'status'        => '✅ Implemented',
					'status_key'    => 'implemented',
					'applicable'    => true,
					'justification' => 'Core ISMS requirement',
					'description'   => 'ISMS Policy document created
Security objectives defined
Management approval obtained
Published and communicated to all personnel',
				),
				1  =>
				array(
					'id'            => 'A.5.2',
					'name'          => 'Information Security Roles and Responsibilities',
					'status'        => '✅ Implemented',
					'status_key'    => 'implemented',
					'applicable'    => true,
					'justification' => 'Essential for accountability',
					'description'   => 'Roles defined in ISMS Policy (Section 5)
CISO role established
Development, operations, and support team responsibilities documented
RACI matrix maintained',
				),
				2  =>
				array(
					'id'            => 'A.5.3',
					'name'          => 'Segregation of Duties',
					'status'        => '✅ Implemented',
					'status_key'    => 'implemented',
					'applicable'    => true,
					'justification' => 'Prevents conflicts of interest and fraud',
					'description'   => 'Code review requires different developer than author
Deployment approval separate from development
Security testing independent from development
Administrative functions separated from operations',
				),
				3  =>
				array(
					'id'            => 'A.5.4',
					'name'          => 'Management Responsibilities',
					'status'        => '✅ Implemented',
					'status_key'    => 'implemented',
					'applicable'    => true,
					'justification' => 'Leadership commitment required',
					'description'   => 'Management approval of ISMS policy
Resource allocation for security
Regular management reviews (semi-annual)
Security performance oversight',
				),
				4  =>
				array(
					'id'            => 'A.5.5',
					'name'          => 'Contact with Authorities',
					'status'        => '✅ Implemented',
					'status_key'    => 'implemented',
					'applicable'    => true,
					'justification' => 'Legal compliance and incident response',
					'description'   => 'Security contact: security@nvdigitalsolutions.com
Data protection authorities contact procedures
Law enforcement liaison procedures
WordPress.org security team contact',
				),
				5  =>
				array(
					'id'            => 'A.5.6',
					'name'          => 'Contact with Special Interest Groups',
					'status'        => '✅ Implemented',
					'status_key'    => 'implemented',
					'applicable'    => true,
					'justification' => 'Stay informed of security threats',
					'description'   => 'WordPress security team membership
OWASP community participation
Security mailing list subscriptions
GitHub security advisories monitoring',
				),
				6  =>
				array(
					'id'            => 'A.5.7',
					'name'          => 'Threat Intelligence',
					'status'        => '✅ Implemented',
					'status_key'    => 'implemented',
					'applicable'    => true,
					'justification' => 'Proactive threat awareness',
					'description'   => 'GitHub Dependabot alerts
WordPress security announcements monitoring
CVE database monitoring for dependencies
Security research community engagement',
				),
				7  =>
				array(
					'id'            => 'A.5.8',
					'name'          => 'Information Security in Project Management',
					'status'        => '✅ Implemented',
					'status_key'    => 'implemented',
					'applicable'    => true,
					'justification' => 'Security by design',
					'description'   => 'Comprehensive security project management framework
Security requirements template for all projects
Mandatory security gates (Design, Code Review, Pre-Release)
GitHub integration with security labels and branch protection
Security review process with 3 levels (Standard, Enhanced, Critical)
Security risk register and assessment matrix
Security milestones and sign-off procedures
Security metrics and dashboard reporting',
				),
				8  =>
				array(
					'id'            => 'A.5.9',
					'name'          => 'Inventory of Information and Other Associated Assets',
					'status'        => '✅ Implemented',
					'status_key'    => 'implemented',
					'applicable'    => true,
					'justification' => 'Asset management foundation',
					'description'   => 'Automated asset discovery system for all plugin components
Comprehensive asset register with classification tagging (Public, Internal, Confidential, Restricted)
Asset ownership documentation for all discovered assets
Source code inventory (includes/, core/, shared/, addons/ directories)
Configuration inventory (WordPress options, encryption keys, API credentials)
Third-party integration inventory (OpenAI, Gemini, Ollama, HuggingFace, JetEngine, WooCommerce, Elementor)
Data storage inventory (Custom Post Types, user metadata, chat transcripts)
Documentation inventory (README, SECURITY, compliance documentation)
Weekly automated discovery via cron job
REST API for asset management (mcp-ai/v1/assets/*)
Admin dashboard for viewing and filtering assets',
				),
				9  =>
				array(
					'id'            => 'A.5.10',
					'name'          => 'Acceptable Use of Information and Other Associated Assets',
					'status'        => '✅ Implemented',
					'status_key'    => 'implemented',
					'applicable'    => true,
					'justification' => 'Define acceptable usage',
					'description'   => 'Comprehensive Acceptable Use Policy (AUP) covering all information assets (700+ lines)
14 sections covering acceptable use, unacceptable use, monitoring, compliance
User responsibilities for authentication, data handling, software usage, network usage, email
Mobile device security and remote work policies included
Acknowledgment mechanism with annual re-certification required
Training integration with onboarding process
Enforcement through disciplinary process (A.6.4)',
				),
				10 =>
				array(
					'id'            => 'A.5.11',
					'name'          => 'Return of Assets',
					'status'        => '✅ Implemented',
					'status_key'    => 'implemented',
					'applicable'    => true,
					'justification' => 'Offboarding procedures',
					'description'   => 'Comprehensive asset return procedures for physical, digital, and intellectual property
Asset return checklist with physical assets, digital access, and data confirmation
Automated access revocation procedures for WordPress, GitHub, and third-party services
Asset return form with required signatures
24-hour access revocation timeline
Asset inventory updates upon termination',
				),
				11 =>
				array(
					'id'            => 'A.5.12',
					'name'          => 'Classification of Information',
					'status'        => '✅ Implemented',
					'status_key'    => 'implemented',
					'applicable'    => true,
					'justification' => 'Risk-based protection',
					'description'   => 'Four classification levels: Public, Internal, Confidential, Restricted
Classification documented in ISMS Policy
Handling requirements per classification',
				),
				12 =>
				array(
					'id'            => 'A.5.13',
					'name'          => 'Labelling of Information',
					'status'        => '✅ Implemented',
					'status_key'    => 'implemented',
					'applicable'    => true,
					'justification' => 'Visual classification indicators',
					'description'   => 'Document classification headers in all compliance documents
Code comments for sensitive sections
Automated classification labeling system for posts and assistants
Four-level classification meta box (Public, Internal, Confidential, Restricted)
Visual classification badges in admin UI
Classification column in post lists
Auto-classification based on content patterns',
				),
				13 =>
				array(
					'id'            => 'A.5.14',
					'name'          => 'Information Transfer',
					'status'        => '✅ Implemented',
					'status_key'    => 'implemented',
					'applicable'    => true,
					'justification' => 'Secure data transmission',
					'description'   => 'HTTPS/TLS for all API communications
Encrypted storage for sensitive data
Secure protocols for third-party integrations',
				),
				14 =>
				array(
					'id'            => 'A.5.15',
					'name'          => 'Access Control',
					'status'        => '✅ Implemented',
					'status_key'    => 'implemented',
					'applicable'    => true,
					'justification' => 'Core security control',
					'description'   => 'WordPress role-based access control (RBAC)
Capability-based permissions for tools
API key authentication
Guest token system for public access',
				),
				15 =>
				array(
					'id'            => 'A.5.16',
					'name'          => 'Identity Management',
					'status'        => '✅ Implemented',
					'status_key'    => 'implemented',
					'applicable'    => true,
					'justification' => 'User lifecycle management',
					'description'   => 'WordPress user management integration
Unique identifiers per user
User registration and deactivation procedures',
				),
				16 =>
				array(
					'id'            => 'A.5.17',
					'name'          => 'Authentication Information',
					'status'        => '✅ Implemented',
					'status_key'    => 'implemented',
					'applicable'    => true,
					'justification' => 'Credential security',
					'description'   => 'Strong password requirements (WordPress integration)
Credential hashing (bcrypt via WordPress)
API key encryption at rest
Master key protection (root security key)',
				),
				17 =>
				array(
					'id'            => 'A.5.18',
					'name'          => 'Access Rights',
					'status'        => '✅ Implemented',
					'status_key'    => 'implemented',
					'applicable'    => true,
					'justification' => 'Least privilege principle',
					'description'   => 'WordPress capability system
Per-assistant tool permissions
API rate limiting per user
Regular access review procedures',
				),
				18 =>
				array(
					'id'            => 'A.5.19',
					'name'          => 'Information Security in Supplier Relationships',
					'status'        => '✅ Implemented',
					'status_key'    => 'implemented',
					'applicable'    => true,
					'justification' => 'Third-party risk management',
					'description'   => 'Comprehensive supplier security management system
Automated supplier registry with security assessments for all critical vendors
Vendor security questionnaires and evaluation framework
Three-tier risk categorization (Critical, Important, Low Risk)
Performance monitoring and incident tracking
Quarterly review scheduling with automated reminders
Assessment of OpenAI, Google, GitHub, Composer, NPM, and other critical suppliers',
				),
				19 =>
				array(
					'id'            => 'A.5.20',
					'name'          => 'Addressing Information Security Within Supplier Agreements',
					'status'        => '✅ Implemented',
					'status_key'    => 'implemented',
					'applicable'    => true,
					'justification' => 'Contractual security obligations',
					'description'   => 'Security requirements template for supplier contracts
Documentation of SLAs with critical vendors (OpenAI 99.9%, Google 99.95%)
Security clause tracking in supplier registry
Terms of Service acceptance and compliance monitoring
Contractual security requirements enforced for all critical suppliers
Data processing agreements with GDPR-compliant vendors',
				),
				20 =>
				array(
					'id'            => 'A.5.21',
					'name'          => 'Managing Information Security in the ICT Supply Chain',
					'status'        => '✅ Implemented',
					'status_key'    => 'implemented',
					'applicable'    => true,
					'justification' => 'Dependency security',
					'description'   => 'Automated Software Bill of Materials (SBOM) generation in CycloneDX format
Daily dependency vulnerability scanning via cron job
Composer and NPM dependency tracking and audit
Dependency approval workflow and security review process
Lock file enforcement (composer.lock, package-lock.json)
Integration with Dependabot for automated vulnerability alerts
Supply chain risk monitoring dashboard',
				),
				21 =>
				array(
					'id'            => 'A.5.22',
					'name'          => 'Monitoring, Review and Change Management of Supplier Services',
					'status'        => '✅ Implemented',
					'status_key'    => 'implemented',
					'applicable'    => true,
					'justification' => 'Ongoing vendor oversight',
					'description'   => 'Automated quarterly supplier review scheduling
Vendor performance monitoring with uptime tracking (avg 99.85% across all suppliers)
Supplier security incident recording and tracking system
Review notification system with email alerts to administrators
Performance metrics dashboard showing YTD incidents and actual uptime vs. SLA
Overdue review indicators with automatic escalation
Change management tracking for supplier service modifications',
				),
				22 =>
				array(
					'id'            => 'A.5.23',
					'name'          => 'Information Security for Use of Cloud Services',
					'status'        => '✅ Implemented',
					'status_key'    => 'implemented',
					'applicable'    => true,
					'justification' => 'Cloud-hosted infrastructure',
					'description'   => 'OpenAI cloud security review
Google Cloud security assessment
Hosting provider security requirements
Shared responsibility model documentation',
				),
				23 =>
				array(
					'id'            => 'A.5.24',
					'name'          => 'Information Security Incident Management Planning and Preparation',
					'status'        => '✅ Implemented',
					'status_key'    => 'implemented',
					'applicable'    => true,
					'justification' => 'Incident response readiness',
					'description'   => 'Incident management procedure documented
Security contact established (security@nvdigitalsolutions.com)
Incident classification and escalation procedures
Response team roles defined',
				),
				24 =>
				array(
					'id'            => 'A.5.25',
					'name'          => 'Assessment and Decision on Information Security Events',
					'status'        => '✅ Implemented',
					'status_key'    => 'implemented',
					'applicable'    => true,
					'justification' => 'Incident triage',
					'description'   => 'Event severity classification
Impact assessment procedures
Decision criteria for incident declaration',
				),
				25 =>
				array(
					'id'            => 'A.5.26',
					'name'          => 'Response to Information Security Incidents',
					'status'        => '✅ Implemented',
					'status_key'    => 'implemented',
					'applicable'    => true,
					'justification' => 'Incident handling',
					'description'   => 'Documented response procedures
Containment, eradication, recovery steps
Communication protocols
Evidence preservation',
				),
				26 =>
				array(
					'id'            => 'A.5.27',
					'name'          => 'Learning from Information Security Incidents',
					'status'        => '✅ Implemented',
					'status_key'    => 'implemented',
					'applicable'    => true,
					'justification' => 'Continuous improvement',
					'description'   => 'Post-incident review process documented in procedures
Root cause analysis procedures and templates
Incident lessons learned database (Custom Post Type: mcp_ai_lesson)
Trend analysis reporting with quarterly/annual views
Lessons learned tracking with severity and category classification
Admin UI for managing lessons learned
Integration with incident management system',
				),
				27 =>
				array(
					'id'            => 'A.5.28',
					'name'          => 'Collection of Evidence',
					'status'        => '✅ Implemented',
					'status_key'    => 'implemented',
					'applicable'    => true,
					'justification' => 'Forensic readiness',
					'description'   => 'Audit logging (authentication, access, changes)
Log retention (12 months)
Chain of custody procedures',
				),
				28 =>
				array(
					'id'            => 'A.5.29',
					'name'          => 'Information Security During Disruption',
					'status'        => '✅ Implemented',
					'status_key'    => 'implemented',
					'applicable'    => true,
					'justification' => 'Business continuity',
					'description'   => 'Comprehensive Business Continuity Plan with dedicated security section (400+ lines)
Security measures for 5 disruption types: provider outage, infrastructure failure, security incident, personnel unavailability, natural disaster
Emergency access procedures with break-glass protocols and dual approval
Security monitoring requirements during disruption (enhanced 15-min frequency)
Secure failover procedures with SSL verification and authorization checks
Post-disruption security review and lessons learned process
Communication security protocols during emergencies (encrypted channels)
Compliance maintenance during disruptions (GDPR/CCPA, audit trails)',
				),
				29 =>
				array(
					'id'            => 'A.5.30',
					'name'          => 'ICT Readiness for Business Continuity',
					'status'        => '✅ Implemented',
					'status_key'    => 'implemented',
					'applicable'    => true,
					'justification' => 'Technology resilience',
					'description'   => 'Redundancy in AI provider integrations (OpenAI, Gemini, Ollama)
Automatic failover capabilities between providers (< 5 seconds)
Recovery Time Objectives (RTO) defined for all components
Recovery Point Objectives (RPO) defined for all data types
Documented failover procedures and disaster recovery steps
Quarterly failover testing schedule
Monitoring and alerting for provider availability
Backup and recovery procedures documented',
				),
				30 =>
				array(
					'id'            => 'A.5.31',
					'name'          => 'Legal, Statutory, Regulatory and Contractual Requirements',
					'status'        => '✅ Implemented',
					'status_key'    => 'implemented',
					'applicable'    => true,
					'justification' => 'Compliance obligations',
					'description'   => 'GDPR compliance considerations
GPL v3 license compliance
OpenAI/Gemini terms compliance
WordPress.org plugin guidelines compliance',
				),
				31 =>
				array(
					'id'            => 'A.5.32',
					'name'          => 'Intellectual Property Rights',
					'status'        => '✅ Implemented',
					'status_key'    => 'implemented',
					'applicable'    => true,
					'justification' => 'IP protection',
					'description'   => 'GPL v3 license
Copyright notices
Third-party license compliance
Attribution requirements',
				),
				32 =>
				array(
					'id'            => 'A.5.33',
					'name'          => 'Protection of Records',
					'status'        => '✅ Implemented',
					'status_key'    => 'implemented',
					'applicable'    => true,
					'justification' => 'Records management',
					'description'   => 'Version control for all documents (Git)
Backup of critical records
12-month log retention',
				),
				33 =>
				array(
					'id'            => 'A.5.34',
					'name'          => 'Privacy and Protection of PII',
					'status'        => '✅ Implemented',
					'status_key'    => 'implemented',
					'applicable'    => true,
					'justification' => 'Data protection compliance',
					'description'   => 'Minimal PII collection
Data encryption (credentials, sensitive settings)
User consent mechanisms
Data deletion capabilities',
				),
				34 =>
				array(
					'id'            => 'A.5.35',
					'name'          => 'Independent Review of Information Security',
					'status'        => '✅ Implemented',
					'status_key'    => 'implemented',
					'applicable'    => true,
					'justification' => 'Assurance of effectiveness',
					'description'   => 'Code review process (peer review)
Security testing (CodeQL)
Automated quarterly internal audit scheduling
Comprehensive audit management system with finding tracking
Management review process documented
Audit dashboard and statistics reporting',
				),
				35 =>
				array(
					'id'            => 'A.5.36',
					'name'          => 'Compliance with Policies, Rules and Standards for Information Security',
					'status'        => '✅ Implemented',
					'status_key'    => 'implemented',
					'applicable'    => true,
					'justification' => 'Policy enforcement',
					'description'   => 'ISMS policy enforcement
WordPress Coding Standards (WPCS) compliance
Security coding standards (OWASP)',
				),
				36 =>
				array(
					'id'            => 'A.5.37',
					'name'          => 'Documented Operating Procedures',
					'status'        => '✅ Implemented',
					'status_key'    => 'implemented',
					'applicable'    => true,
					'justification' => 'Operational consistency',
					'description'   => 'Development procedures documented
Deployment procedures documented
Security procedures documented',
				),
				37 =>
				array(
					'id'            => 'A.6.1',
					'name'          => 'Screening',
					'status'        => '✅ Implemented',
					'status_key'    => 'implemented',
					'applicable'    => true,
					'justification' => 'Trusted personnel',
					'description'   => 'Three-level screening framework (Basic, Standard, Enhanced)
Role-based screening matrix for all positions
Comprehensive background screening procedure (identity, references, employment history)
Screening documentation requirements
Periodic re-screening every 3 years for sensitive roles
Security questionnaire and consent forms',
				),
				38 =>
				array(
					'id'            => 'A.6.2',
					'name'          => 'Terms and Conditions of Employment',
					'status'        => '✅ Implemented',
					'status_key'    => 'implemented',
					'applicable'    => true,
					'justification' => 'Contractual security obligations',
					'description'   => 'Mandatory security clauses in all employment agreements (7 clauses)
Comprehensive non-disclosure agreements (NDA) with defined scope and duration
Security responsibilities documented by role (All Employees, Developers, Administrators, Security Team)
Required acknowledgment and acceptance signatures
Annual security policy acknowledgment
Confidentiality, acceptable use, data protection, and IP rights clauses',
				),
				39 =>
				array(
					'id'            => 'A.6.3',
					'name'          => 'Information Security Awareness, Education and Training',
					'status'        => '✅ Implemented',
					'status_key'    => 'implemented',
					'applicable'    => true,
					'justification' => 'Human firewall - Essential for maintaining security culture',
					'description'   => 'Comprehensive security training system with role-based training paths
Five mandatory training modules covering ISO 27001, secure coding, WordPress security, incident response, and data protection
Training completion tracking via user metadata
Annual refresher training with automated email reminders
Training statistics dashboard for administrators
User training dashboard for viewing and completing modules
Training modules stored as custom post type (mcp_ai_training)
REST API for programmatic training management (mcp-ai/v1/training/*)
Security awareness content for all users
Technical security training for developers
Policy and compliance training
Incident response procedures training',
				),
				40 =>
				array(
					'id'            => 'A.6.4',
					'name'          => 'Disciplinary Process',
					'status'        => '✅ Implemented',
					'status_key'    => 'implemented',
					'applicable'    => true,
					'justification' => 'Policy enforcement',
					'description'   => 'Formal disciplinary process for security policy violations (700+ lines)
4 violation categories with severity levels and specific examples
7-step disciplinary process: detection → assessment → investigation → action determination → implementation → notification → appeal
7 action types: verbal warning, written warning, final warning, suspension, demotion, termination, legal action
Investigation procedures with timelines (2-30 days based on severity)
Decision-making authority matrix by violation category
Appeal process with independent review panel
Post-action monitoring and retraining requirements
Documentation and record retention (1-7 years based on action type)',
				),
				41 =>
				array(
					'id'            => 'A.6.5',
					'name'          => 'Responsibilities After Termination or Change of Employment',
					'status'        => '✅ Implemented',
					'status_key'    => 'implemented',
					'applicable'    => true,
					'justification' => 'Post-employment security',
					'description'   => 'Comprehensive post-termination obligations (3-year confidentiality minimum)
Non-compete and non-solicitation agreements where legally enforceable
Knowledge transfer requirements with detailed handover checklist
Exit interview with security focus (7 security questions)
Post-termination monitoring (30-day and 90-day reviews)
Legal remedies for breaches documented
Continuing confidentiality and non-disclosure obligations',
				),
				42 =>
				array(
					'id'            => 'A.6.6',
					'name'          => 'Confidentiality or Non-Disclosure Agreements',
					'status'        => '✅ Implemented',
					'status_key'    => 'implemented',
					'applicable'    => true,
					'justification' => 'Information protection',
					'description'   => 'Comprehensive NDA templates (Employee, Contractor, Mutual, Security Researcher)
NDA lifecycle management with registration and tracking system
Breach response procedures and enforcement mechanisms
Annual reviews and compliance monitoring',
				),
				43 =>
				array(
					'id'            => 'A.6.7',
					'name'          => 'Remote Working',
					'status'        => '✅ Implemented',
					'status_key'    => 'implemented',
					'applicable'    => true,
					'justification' => 'Distributed team security',
					'description'   => 'VPN or secure access requirements
Endpoint security requirements
HTTPS/TLS for all communications
Multi-factor authentication',
				),
				44 =>
				array(
					'id'            => 'A.6.8',
					'name'          => 'Information Security Event Reporting',
					'status'        => '✅ Implemented',
					'status_key'    => 'implemented',
					'applicable'    => true,
					'justification' => 'Incident awareness',
					'description'   => 'Security reporting contact (security@nvdigitalsolutions.com)
GitHub security advisory reporting
Internal reporting procedures',
				),
				45 =>
				array(
					'id'            => 'A.7.1',
					'name'          => 'Physical Security Perimeters',
					'status'        => '❌ Not Applicable',
					'status_key'    => 'not_applicable',
					'applicable'    => false,
					'justification' => 'No physical facilities under direct control; cloud-hosted infrastructure managed by providers with ISO 27001 certification',
					'description'   => '',
				),
				46 =>
				array(
					'id'            => 'A.7.2',
					'name'          => 'Physical Entry',
					'status'        => '❌ Not Applicable',
					'status_key'    => 'not_applicable',
					'applicable'    => false,
					'justification' => 'See A.7.1',
					'description'   => '',
				),
				47 =>
				array(
					'id'            => 'A.7.3',
					'name'          => 'Securing Offices, Rooms and Facilities',
					'status'        => '❌ Not Applicable',
					'status_key'    => 'not_applicable',
					'applicable'    => false,
					'justification' => 'Remote work environment, no central office facilities',
					'description'   => '',
				),
				48 =>
				array(
					'id'            => 'A.7.4',
					'name'          => 'Physical Security Monitoring',
					'status'        => '❌ Not Applicable',
					'status_key'    => 'not_applicable',
					'applicable'    => false,
					'justification' => 'See A.7.1',
					'description'   => '',
				),
				49 =>
				array(
					'id'            => 'A.7.5',
					'name'          => 'Protecting Against Physical and Environmental Threats',
					'status'        => '❌ Not Applicable',
					'status_key'    => 'not_applicable',
					'applicable'    => false,
					'justification' => 'Managed by cloud hosting providers',
					'description'   => '',
				),
				50 =>
				array(
					'id'            => 'A.7.6',
					'name'          => 'Working in Secure Areas',
					'status'        => '❌ Not Applicable',
					'status_key'    => 'not_applicable',
					'applicable'    => false,
					'justification' => 'No designated secure areas',
					'description'   => '',
				),
				51 =>
				array(
					'id'            => 'A.7.7',
					'name'          => 'Clear Desk and Clear Screen',
					'status'        => '✅ Implemented',
					'status_key'    => 'implemented',
					'applicable'    => true,
					'justification' => 'Remote worker endpoint security',
					'description'   => 'Comprehensive clear desk and clear screen policy for all work locations
Mandatory screen lock after 5 minutes (PCs) or 2 minutes (mobile)
Privacy screen requirements for public spaces
Document handling and secure disposal procedures
Quarterly audit program with compliance monitoring',
				),
				52 =>
				array(
					'id'            => 'A.7.8',
					'name'          => 'Equipment Siting and Protection',
					'status'        => '✅ Implemented',
					'status_key'    => 'implemented',
					'applicable'    => false,
					'justification' => 'Developer endpoints',
					'description'   => 'Home office equipment protection standards
Environmental controls (temperature, humidity, power protection)
Physical access control requirements (locking, cable locks)
Equipment transport and storage guidelines
Surge protectors and UPS requirements',
				),
				53 =>
				array(
					'id'            => 'A.7.9',
					'name'          => 'Security of Assets Off-Premises',
					'status'        => '✅ Implemented',
					'status_key'    => 'implemented',
					'applicable'    => true,
					'justification' => 'Remote work equipment',
					'description'   => 'Comprehensive mobile device management (MDM) policy and implementation
VPN requirements for all remote access to organizational systems
Device encryption, authentication, and security software requirements
Physical device custody and loss/theft response procedures
BYOD policy with work profile data separation
Travel security guidelines (domestic and international)',
				),
				54 =>
				array(
					'id'            => 'A.7.10',
					'name'          => 'Storage Media',
					'status'        => '✅ Implemented',
					'status_key'    => 'implemented',
					'applicable'    => true,
					'justification' => 'Secure data storage',
					'description'   => 'Encrypted storage for sensitive data
Database encryption at rest
Secure credential storage',
				),
				55 =>
				array(
					'id'            => 'A.7.11',
					'name'          => 'Supporting Utilities',
					'status'        => '❌ Not Applicable',
					'status_key'    => 'not_applicable',
					'applicable'    => false,
					'justification' => 'Managed by cloud providers',
					'description'   => '',
				),
				56 =>
				array(
					'id'            => 'A.7.12',
					'name'          => 'Cabling Security',
					'status'        => '❌ Not Applicable',
					'status_key'    => 'not_applicable',
					'applicable'    => false,
					'justification' => 'No physical infrastructure management',
					'description'   => '',
				),
				57 =>
				array(
					'id'            => 'A.7.13',
					'name'          => 'Equipment Maintenance',
					'status'        => '❌ Not Applicable',
					'status_key'    => 'not_applicable',
					'applicable'    => false,
					'justification' => 'Cloud provider responsibility',
					'description'   => '',
				),
				58 =>
				array(
					'id'            => 'A.7.14',
					'name'          => 'Secure Disposal or Reuse of Equipment',
					'status'        => '✅ Implemented',
					'status_key'    => 'implemented',
					'applicable'    => true,
					'justification' => 'Developer endpoint disposal',
					'description'   => 'Comprehensive equipment disposal and reuse procedures
Data sanitization methods by device type (NIST SP 800-88, DoD 5220.22-M)
Physical destruction standards for sensitive data
Lost/stolen device response procedures with remote wipe
Vendor selection criteria and certification requirements
Complete documentation and audit trail requirements',
				),
				59 =>
				array(
					'id'            => 'A.8.1',
					'name'          => 'User Endpoint Devices',
					'status'        => '✅ Implemented',
					'status_key'    => 'implemented',
					'applicable'    => true,
					'justification' => 'Developer devices',
					'description'   => 'Mandatory endpoint security software (antivirus, EDR, firewall)
Configuration standards for Windows, macOS, and Linux endpoints
Patch management (OS within 30 days, critical within 7 days)
Centralized endpoint management and compliance monitoring
Full disk encryption required for all devices',
				),
				60 =>
				array(
					'id'            => 'A.8.2',
					'name'          => 'Privileged Access Rights',
					'status'        => '✅ Implemented',
					'status_key'    => 'implemented',
					'applicable'    => true,
					'justification' => 'Administrative access control',
					'description'   => 'WordPress administrator roles
Repository administrator access controls
Limited privileged access (need-to-know)
Audit logging of privileged actions',
				),
				61 =>
				array(
					'id'            => 'A.8.3',
					'name'          => 'Information Access Restriction',
					'status'        => '✅ Implemented',
					'status_key'    => 'implemented',
					'applicable'    => true,
					'justification' => 'Least privilege principle',
					'description'   => 'WordPress capability-based access control
Per-assistant tool permissions
API authentication and authorization',
				),
				62 =>
				array(
					'id'            => 'A.8.4',
					'name'          => 'Access to Source Code',
					'status'        => '✅ Implemented',
					'status_key'    => 'implemented',
					'applicable'    => true,
					'justification' => 'Intellectual property protection',
					'description'   => 'GitHub access controls
Branch protection rules
Code review requirements
Open source with GPL v3 (public access controlled by license)',
				),
				63 =>
				array(
					'id'            => 'A.8.5',
					'name'          => 'Secure Authentication',
					'status'        => '✅ Implemented',
					'status_key'    => 'implemented',
					'applicable'    => true,
					'justification' => 'Core security control',
					'description'   => 'WordPress authentication integration
Multi-factor authentication support
API key authentication
JWT authentication (Simple JWT plugin)
Auth0 integration',
				),
				64 =>
				array(
					'id'            => 'A.8.6',
					'name'          => 'Capacity Management',
					'status'        => '✅ Implemented',
					'status_key'    => 'implemented',
					'applicable'    => true,
					'justification' => 'Performance and availability',
					'description'   => 'Comprehensive capacity monitoring (CPU, memory, disk, bandwidth, API limits)
Alert thresholds (warning at 70%, critical at 85%)
Rate limiting implementation for API endpoints
Monthly capacity review and quarterly planning process
Capacity forecasting and scaling procedures',
				),
				65 =>
				array(
					'id'            => 'A.8.7',
					'name'          => 'Protection Against Malware',
					'status'        => '✅ Implemented',
					'status_key'    => 'implemented',
					'applicable'    => true,
					'justification' => 'Code integrity',
					'description'   => 'Multi-layered malware protection (prevention, detection, response)
WordPress site-level malware scanning
Dependency vulnerability scanning (Dependabot, Composer/npm audit)
Automated malware scanning in CI/CD pipeline (ClamAV, secret scanning)
User training on malware awareness (quarterly with phishing simulations)',
				),
				66 =>
				array(
					'id'            => 'A.8.8',
					'name'          => 'Management of Technical Vulnerabilities',
					'status'        => '✅ Implemented',
					'status_key'    => 'implemented',
					'applicable'    => true,
					'justification' => 'Proactive vulnerability management',
					'description'   => 'CodeQL security scanning
Dependabot vulnerability alerts
Regular dependency updates
Documented patch management process',
				),
				67 =>
				array(
					'id'            => 'A.8.9',
					'name'          => 'Configuration Management',
					'status'        => '✅ Implemented',
					'status_key'    => 'implemented',
					'applicable'    => true,
					'justification' => 'System integrity',
					'description'   => 'Version control for all code and configuration
Configuration settings in database
Environment-specific configurations',
				),
				68 =>
				array(
					'id'            => 'A.8.10',
					'name'          => 'Information Deletion',
					'status'        => '✅ Implemented',
					'status_key'    => 'implemented',
					'applicable'    => true,
					'justification' => 'Data lifecycle management',
					'description'   => 'Secure deletion of sensitive data (crypto-shredding)
Log retention and deletion (12 months)
Transcript cleanup features',
				),
				69 =>
				array(
					'id'            => 'A.8.11',
					'name'          => 'Data Masking',
					'status'        => '✅ Implemented',
					'status_key'    => 'implemented',
					'applicable'    => true,
					'justification' => 'PII protection',
					'description'   => 'Comprehensive data masking procedures and code library
API key masking in UI (show last 4 characters only)
Email, phone, IP address masking functions
Automatic sensitive data masking in logs
Test data anonymization scripts
Production data sanitization procedures for test databases',
				),
				70 =>
				array(
					'id'            => 'A.8.12',
					'name'          => 'Data Leakage Prevention',
					'status'        => '✅ Implemented',
					'status_key'    => 'implemented',
					'applicable'    => true,
					'justification' => 'Information protection',
					'description'   => 'Sensitive data encryption
Access controls on confidential information
Audit logging of data access
Rate limiting to prevent mass data extraction',
				),
				71 =>
				array(
					'id'            => 'A.8.13',
					'name'          => 'Information Backup',
					'status'        => '✅ Implemented',
					'status_key'    => 'implemented',
					'applicable'    => true,
					'justification' => 'Data availability and recovery',
					'description'   => 'Database backup procedures
Version control as code backup
Backup retention policies',
				),
				72 =>
				array(
					'id'            => 'A.8.14',
					'name'          => 'Redundancy of Information Processing Facilities',
					'status'        => '✅ Implemented',
					'status_key'    => 'implemented',
					'applicable'    => true,
					'justification' => 'High availability',
					'description'   => 'Multiple AI provider support (OpenAI, Gemini, Ollama)
Failover capabilities
Distributed deployment support',
				),
				73 =>
				array(
					'id'            => 'A.8.15',
					'name'          => 'Logging',
					'status'        => '✅ Implemented',
					'status_key'    => 'implemented',
					'applicable'    => true,
					'justification' => 'Accountability and forensics',
					'description'   => 'Authentication event logging
Access logging (tool execution, data access)
Configuration change logging
Error and exception logging',
				),
				74 =>
				array(
					'id'            => 'A.8.16',
					'name'          => 'Monitoring Activities',
					'status'        => '✅ Implemented',
					'status_key'    => 'implemented',
					'applicable'    => true,
					'justification' => 'Threat detection',
					'description'   => 'Security event monitoring
Rate limiting and abuse detection
Nefarious usage monitoring
Performance monitoring',
				),
				75 =>
				array(
					'id'            => 'A.8.17',
					'name'          => 'Clock Synchronization',
					'status'        => '✅ Implemented',
					'status_key'    => 'implemented',
					'applicable'    => true,
					'justification' => 'Accurate time for logs and events',
					'description'   => 'Server time synchronization (NTP via hosting provider)
Timestamps in logs (UTC)
Time-based operations use server time',
				),
				76 =>
				array(
					'id'            => 'A.8.18',
					'name'          => 'Use of Privileged Utility Programs',
					'status'        => '✅ Implemented',
					'status_key'    => 'implemented',
					'applicable'    => true,
					'justification' => 'Administrative tool security',
					'description'   => 'WP-CLI access controls
Administrative functions require elevated privileges
Audit logging of administrative actions',
				),
				77 =>
				array(
					'id'            => 'A.8.19',
					'name'          => 'Installation of Software on Operational Systems',
					'status'        => '✅ Implemented',
					'status_key'    => 'implemented',
					'applicable'    => true,
					'justification' => 'System integrity',
					'description'   => 'WordPress plugin installation controls
Dependency management (Composer, NPM)
Code review before deployment
Version pinning for dependencies',
				),
				78 =>
				array(
					'id'            => 'A.8.20',
					'name'          => 'Networks Security',
					'status'        => '✅ Implemented',
					'status_key'    => 'implemented',
					'applicable'    => true,
					'justification' => 'Network layer protection',
					'description'   => 'HTTPS/TLS for all communications
API endpoint security
Network segmentation (hosting provider level)',
				),
				79 =>
				array(
					'id'            => 'A.8.21',
					'name'          => 'Security of Network Services',
					'status'        => '✅ Implemented',
					'status_key'    => 'implemented',
					'applicable'    => true,
					'justification' => 'Service availability and security',
					'description'   => 'API authentication and authorization
Rate limiting
DDoS protection (hosting provider)',
				),
				80 =>
				array(
					'id'            => 'A.8.22',
					'name'          => 'Segregation of Networks',
					'status'        => '✅ Implemented',
					'status_key'    => 'implemented',
					'applicable'    => false,
					'justification' => 'Development/production separation',
					'description'   => 'Strict environment segregation (production, staging, development, testing)
Firewall rules enforcing environment isolation
No production data in non-production environments (anonymized only)
Deployment pipeline security with GitOps
Access control matrix by environment
Network isolation verification procedures (quarterly testing)',
				),
				81 =>
				array(
					'id'            => 'A.8.23',
					'name'          => 'Web Filtering',
					'status'        => '❌ Not Applicable',
					'status_key'    => 'not_applicable',
					'applicable'    => false,
					'justification' => 'No centralized network infrastructure; individual developer responsibility',
					'description'   => '',
				),
				82 =>
				array(
					'id'            => 'A.8.24',
					'name'          => 'Use of Cryptography',
					'status'        => '✅ Implemented',
					'status_key'    => 'implemented',
					'applicable'    => true,
					'justification' => 'Data confidentiality and integrity',
					'description'   => 'TLS 1.2+ for data in transit
AES-256 encryption for data at rest (credentials)
bcrypt for password hashing (WordPress integration)
Cryptographically secure random number generation',
				),
				83 =>
				array(
					'id'            => 'A.8.25',
					'name'          => 'Secure Development Life Cycle',
					'status'        => '✅ Implemented',
					'status_key'    => 'implemented',
					'applicable'    => true,
					'justification' => 'Secure software development',
					'description'   => 'Security requirements in planning
Secure coding guidelines (WordPress standards, OWASP)
Code review process
Security testing (CodeQL)
Vulnerability management',
				),
				84 =>
				array(
					'id'            => 'A.8.26',
					'name'          => 'Application Security Requirements',
					'status'        => '✅ Implemented',
					'status_key'    => 'implemented',
					'applicable'    => true,
					'justification' => 'Application-level security',
					'description'   => 'Input validation and sanitization
Output encoding and escaping
Authentication and authorization
Error handling',
				),
				85 =>
				array(
					'id'            => 'A.8.27',
					'name'          => 'Secure System Architecture and Engineering Principles',
					'status'        => '✅ Implemented',
					'status_key'    => 'implemented',
					'applicable'    => true,
					'justification' => 'Architectural security',
					'description'   => 'Defense in depth (multiple security layers)
Principle of least privilege
Fail-safe defaults
Separation of concerns',
				),
				86 =>
				array(
					'id'            => 'A.8.28',
					'name'          => 'Secure Coding',
					'status'        => '✅ Implemented',
					'status_key'    => 'implemented',
					'applicable'    => true,
					'justification' => 'Vulnerability prevention',
					'description'   => 'WordPress Coding Standards (WPCS)
OWASP Top 10 guidelines
Input sanitization and output escaping
Prepared statements for database queries
Nonce verification for state changes',
				),
				87 =>
				array(
					'id'            => 'A.8.29',
					'name'          => 'Security Testing in Development and Acceptance',
					'status'        => '✅ Implemented',
					'status_key'    => 'implemented',
					'applicable'    => true,
					'justification' => 'Vulnerability detection',
					'description'   => 'Automated security testing (CodeQL)
Unit tests for security functions
Integration tests
Code review with security focus',
				),
				88 =>
				array(
					'id'            => 'A.8.30',
					'name'          => 'Outsourced Development',
					'status'        => '✅ Implemented',
					'status_key'    => 'implemented',
					'applicable'    => false,
					'justification' => 'Third-party contributor management',
					'description'   => 'Comprehensive External Contribution Security Review Procedures (700+ lines)
Contributor License Agreement (CLA) requirement with automated checking
Identity verification and trust level system (4 categories: anonymous, community, trusted, security researcher)
Automated security scanning: CodeQL analysis, dependency vulnerability checks, secret scanning
Manual security review with 10-point comprehensive checklist
Risk-based review levels (Low/Medium/High) with escalating approval requirements
Responsible vulnerability disclosure procedures with coordinated disclosure timeline
Malicious code detection and incident response procedures
Branch protection rules enforcing 2 reviewers and status checks
External contribution monitoring and trust level advancement',
				),
				89 =>
				array(
					'id'            => 'A.8.31',
					'name'          => 'Separation of Development, Test and Production Environments',
					'status'        => '✅ Implemented',
					'status_key'    => 'implemented',
					'applicable'    => true,
					'justification' => 'Environment isolation',
					'description'   => 'Three distinct environments: Development (local/Docker), Staging (mirrored prod), Production (live)
Physical/logical separation with isolated infrastructure and databases
Environment-specific configurations (WP_MCP_AI_ENV, debug settings)
Strict access control matrix (developers no prod access, admins audited)
Data flow controls (code-only promotion, anonymized data only to lower envs)
Deployment gates (2 gates: dev→staging, staging→prod with approvals)
Automated environment validation checks
Separate API keys and encryption keys per environment',
				),
				90 =>
				array(
					'id'            => 'A.8.32',
					'name'          => 'Change Management',
					'status'        => '✅ Implemented',
					'status_key'    => 'implemented',
					'applicable'    => true,
					'justification' => 'Controlled changes',
					'description'   => 'Formal change management process with 3 categories (Standard, Normal, Emergency)
Comprehensive change request template with 9 sections
Change approval workflow with technical, security, and management reviews
Risk-based approval requirements (high-risk requires management/CISO approval)
Deployment gates with pre/post-implementation checklists
Documented rollback procedures with clear triggers
Emergency change procedure with expedited approval (CISO required)
Change tracking and monthly reporting (success rate, rollback frequency, etc.)
Automated change tracking via Git commits and PR system',
				),
				91 =>
				array(
					'id'            => 'A.8.33',
					'name'          => 'Test Information',
					'status'        => '✅ Implemented',
					'status_key'    => 'implemented',
					'applicable'    => true,
					'justification' => 'Protect production data',
					'description'   => 'Comprehensive test data generation procedures (synthetic data preferred)
Production data anonymization process with email, IP, and PII anonymization
Test data protection controls and access logs
Automated test data cleanup procedures (7-30 day retention)
Test data lifecycle management (creation → use → cleanup)
GDPR/CCPA compliant test data handling
Four test data categories: Synthetic, Anonymized, Subsets (restricted), Prohibited',
				),
				92 =>
				array(
					'id'            => 'A.8.34',
					'name'          => 'Protection of Information Systems During Audit Testing',
					'status'        => '🏆 **100% COMPLIANCE ACHIEVED - ALL 83 APPLICABLE CONTROLS IMPLEMENTED**',
					'status_key'    => 'implemented',
					'applicable'    => true,
					'justification' => 'Minimize audit impact',
					'description'   => 'Comprehensive Audit Protection Procedures (720+ lines)
Pre-audit risk assessment with impact analysis and mitigation planning
Auditor access control with custom WordPress "auditor" role (read-only capabilities)
Audit account management with time-limited access and MFA requirement
Access level matrix defining permissions by auditor type and resource
Sensitive data protection with masking, anonymization, and encryption
Audit environment isolation strategy (read-only production or isolated clone)
Enhanced logging and real-time monitoring during audit activities
Performance impact management and scheduling best practices
Audit-related incident response procedures
Post-audit cleanup and account deactivation with 30-day retention
Post-audit security review within 7 days',
				),
			);
		}

		/**
		 * Get ISO 27001 statistics.
		 *
		 * @return array Statistics with counts for each status.
		 */
		public static function get_iso27001_stats() {
			return array(
				'implemented'    => 83,
				'partial'        => 0,
				'planned'        => 0,
				'not_applicable' => 10,
				'total'          => 93,
			);
		}

		/**
		 * Get SOC 2 compliance percentage.
		 *
		 * Calculates compliance percentage based on implemented Trust Services Criteria.
		 * This is a placeholder that should be updated with actual SOC 2 parsing.
		 *
		 * @return int Compliance percentage (0-100).
		 */
		public static function get_soc2_compliance() {
			// This would be calculated from SOC 2 SoA file.
			// For now, return a default based on ISO 27001 implementation.
			$iso_stats        = self::get_iso27001_stats();
			$total_applicable = $iso_stats['total'] - $iso_stats['not_applicable'];

			if ( $total_applicable > 0 ) {
				return round( ( $iso_stats['implemented'] / $total_applicable ) * 100 );
			}

			return 0;
		}

		/**
		 * Get HIPAA compliance percentage.
		 *
		 * Calculates compliance percentage based on implemented HIPAA Security Rule safeguards.
		 * This is a placeholder that should be updated with actual HIPAA parsing.
		 *
		 * @return int Compliance percentage (0-100).
		 */
		public static function get_hipaa_compliance() {
			// This would be calculated from HIPAA SoA file.
			// For now, return a default based on ISO 27001 implementation.
			$iso_stats        = self::get_iso27001_stats();
			$total_applicable = $iso_stats['total'] - $iso_stats['not_applicable'];

			if ( $total_applicable > 0 ) {
				return round( ( $iso_stats['implemented'] / $total_applicable ) * 100 );
			}

			return 0;
		}
	}
}
