<?php
/**
 * Tests for Pro addon update integrity verification.
 *
 * Covers WP_MCP_AI_Plugin_Updater::verify_pro_installation_integrity() and
 * get_vendor_autoload_files() — the guards that prevent a partially copied
 * Pro vendor tree (missing files referenced by the Composer autoloader) from
 * white-screening the site after an in-place update.
 *
 * @package WP_MCP_AI
 * @author    NV Digital Solutions
 * @copyright Copyright (c) 2025-2026 NV Digital Solutions
 * @license   GPL-3.0-or-later
 */

/**
 * Test the Pro addon vendor integrity verification.
 */
class WP_MCP_AI_Pro_Update_Vendor_Integrity_Test extends WP_UnitTestCase {

	/**
	 * Temp fixture root.
	 *
	 * @var string
	 */
	private $fixture_root = '';

	/**
	 * Set up the fake Pro addon tree.
	 */
	public function setUp(): void {
		parent::setUp();

		if ( ! class_exists( 'WP_MCP_AI_Plugin_Updater' ) ) {
			require_once WP_MCP_AI_PATH . 'includes/class-wp-mcp-ai-plugin-updater.php';
		}

		$this->fixture_root = rtrim( sys_get_temp_dir(), '/\\' ) . '/wp-mcp-ai-pro-verify-' . wp_generate_password( 12, false );

		// Critical files required by VERIFY_PRO_FILES.
		$dirs = array(
			$this->fixture_root . '/vendor/composer',
			$this->fixture_root . '/includes',
		);
		foreach ( $dirs as $dir ) {
			wp_mkdir_p( $dir );
		}

		// A realistic Composer-generated files map referencing two paths.
		$autoload_files = "<?php\n\n// autoload_files.php @generated by Composer\n\n\$vendorDir = dirname(__DIR__);\n\$baseDir = dirname(\$vendorDir);\n\nreturn array(\n    '72243e5536b63e298acb6476f01f1aff' => \$vendorDir . '/thecodingmachine/safe/lib/special_cases.php',\n    '3f648889e687f31c52f949ba8a9d0873' => \$baseDir . '/vendor/composer/ClassLoader.php',\n);\n";
		file_put_contents( $this->fixture_root . '/vendor/composer/autoload_files.php', $autoload_files ); // phpcs:ignore WordPress.WP.AlternativeFunctions.file_system_operations_file_put_contents -- test fixture.

		// Files referenced by the map + the critical safelist.
		$files = array(
			'/vendor/thecodingmachine/safe/lib/special_cases.php',
			'/vendor/composer/ClassLoader.php',
			'/vendor/autoload.php',
			'/vendor/composer/autoload_real.php',
			'/vendor/composer/autoload_static.php',
			'/vendor/composer/InstalledVersions.php',
			'/includes/class-wp-mcp-ai-pro-module-registry.php',
		);
		foreach ( $files as $relative ) {
			$path = $this->fixture_root . $relative;
			wp_mkdir_p( dirname( $path ) );
			file_put_contents( $path, '<?php // fixture' ); // phpcs:ignore WordPress.WP.AlternativeFunctions.file_system_operations_file_put_contents -- test fixture.
		}

		// The main addon file must match the installed addon's entry point.
		if ( defined( 'WP_MCP_AI_PRO_FILE' ) ) {
			$main_file = basename( WP_MCP_AI_PRO_FILE );
			if ( '' !== $main_file ) {
				file_put_contents( $this->fixture_root . '/' . $main_file, '<?php // fixture' ); // phpcs:ignore WordPress.WP.AlternativeFunctions.file_system_operations_file_put_contents -- test fixture.
			}
		}
	}

	/**
	 * Tear down: remove the fixture directory.
	 */
	public function tear_down() {
		$this->remove_fixture();
		parent::tear_down();
	}

	/**
	 * Recursively remove the fixture directory.
	 */
	private function remove_fixture() {
		if ( ! is_dir( $this->fixture_root ) ) {
			return;
		}
		$files = array_diff( scandir( $this->fixture_root ), array( '.', '..' ) );
		foreach ( $files as $file ) {
			$path = $this->fixture_root . '/' . $file;
			if ( is_dir( $path ) ) {
				$this->remove_fixture_subdir( $path );
			} else {
				unlink( $path ); // phpcs:ignore WordPress.WP.AlternativeFunctions.unlink_unlink -- test cleanup.
			}
		}
		rmdir( $this->fixture_root ); // phpcs:ignore WordPress.WP.AlternativeFunctions.rmdir_rmdir,WordPress.WP.AlternativeFunctions.file_system_operations_rmdir -- test cleanup.
	}

	/**
	 * Recursively remove a fixture subdirectory.
	 *
	 * @param string $dir Directory path.
	 */
	private function remove_fixture_subdir( $dir ) {
		$files = array_diff( scandir( $dir ), array( '.', '..' ) );
		foreach ( $files as $file ) {
			$path = $dir . '/' . $file;
			if ( is_dir( $path ) ) {
				$this->remove_fixture_subdir( $path );
			} else {
				unlink( $path ); // phpcs:ignore WordPress.WP.AlternativeFunctions.unlink_unlink -- test cleanup.
			}
		}
		rmdir( $dir ); // phpcs:ignore WordPress.WP.AlternativeFunctions.rmdir_rmdir,WordPress.WP.AlternativeFunctions.file_system_operations_rmdir -- test cleanup.
	}

	/**
	 * Invoke a private static method on the updater class.
	 *
	 * @param string $method Method name.
	 * @param array  $args   Method arguments.
	 * @return mixed Method return value.
	 */
	private function invoke_private( $method, $args ) {
		$reflection = new ReflectionMethod( 'WP_MCP_AI_Plugin_Updater', $method );
		$reflection->setAccessible( true );
		return $reflection->invokeArgs( null, $args );
	}

	/**
	 * Test that an intact vendor tree passes verification.
	 */
	public function test_intact_vendor_tree_passes() {
		$result = $this->invoke_private(
			'verify_pro_installation_integrity',
			array( $this->fixture_root )
		);

		$this->assertTrue( $result );
	}

	/**
	 * Test that a missing files-map entry (the exact special_cases.php class
	 * of failure) is detected and reported with a relative path.
	 */
	public function test_missing_autoloader_referenced_file_detected() {
		unlink( $this->fixture_root . '/vendor/thecodingmachine/safe/lib/special_cases.php' ); // phpcs:ignore WordPress.WP.AlternativeFunctions.unlink_unlink -- simulate partial copy.

		$result = $this->invoke_private(
			'verify_pro_installation_integrity',
			array( $this->fixture_root )
		);

		$this->assertWPError( $result );
		$this->assertSame( 'pro_integrity_check_failed', $result->get_error_code() );
		$this->assertStringContainsString( 'vendor/thecodingmachine/safe/lib/special_cases.php', $result->get_error_message() );
	}

	/**
	 * Test that a missing critical safelist file is detected.
	 */
	public function test_missing_critical_file_detected() {
		unlink( $this->fixture_root . '/vendor/composer/ClassLoader.php' ); // phpcs:ignore WordPress.WP.AlternativeFunctions.unlink_unlink -- simulate partial copy.

		$result = $this->invoke_private(
			'verify_pro_installation_integrity',
			array( $this->fixture_root )
		);

		$this->assertWPError( $result );
		$this->assertSame( 'pro_integrity_check_failed', $result->get_error_code() );
		$this->assertStringContainsString( 'vendor/composer/ClassLoader.php', $result->get_error_message() );
	}

	/**
	 * Test that the autoload files map parser resolves both $vendorDir and
	 * $baseDir entries to absolute paths.
	 */
	public function test_autoload_files_map_parser() {
		$paths = $this->invoke_private(
			'get_vendor_autoload_files',
			array( $this->fixture_root, $this->fixture_root . '/vendor/composer/autoload_files.php' )
		);

		$this->assertIsArray( $paths );
		$this->assertCount( 2, $paths );

		$relative = array();
		foreach ( $paths as $absolute ) {
			$relative[] = str_replace( $this->fixture_root . '/', '', $absolute );
		}

		$this->assertContains( 'vendor/thecodingmachine/safe/lib/special_cases.php', $relative );
		$this->assertContains( 'vendor/composer/ClassLoader.php', $relative );
	}

	/**
	 * Test that the real, committed addons/pro vendor tree verifies clean.
	 * Skips when the repo checkout has no committed vendor tree.
	 */
	public function test_real_pro_vendor_tree_verifies() {
		$pro_root = defined( 'WP_MCP_AI_PRO_PATH' ) ? WP_MCP_AI_PRO_PATH : ( WP_MCP_AI_PATH . 'addons/pro/' );
		$pro_root = untrailingslashit( $pro_root );

		if ( ! is_dir( $pro_root . '/vendor/composer' ) || ! file_exists( $pro_root . '/vendor/composer/autoload_files.php' ) ) {
			$this->markTestSkipped( 'Committed Pro vendor tree not available in this checkout.' );
		}

		$result = $this->invoke_private( 'verify_pro_installation_integrity', array( $pro_root ) );

		// The main-file check ties into WP_MCP_AI_PRO_FILE; when Pro is not
		// booted in the test env the constant may point elsewhere, so only
		// assert the error (if any) is a file-mismatch rather than vendor
		// incompleteness.
		if ( is_wp_error( $result ) ) {
			$this->assertStringContainsString( '.php', $result->get_error_message() );
		} else {
			$this->assertTrue( $result );
		}
	}
}
