<?php
/**
 * Tests for embedded GGUF model slug sanitization.
 *
 * Regression test for the bug where sanitize_key() stripped dots from slugs
 * like "qwen2-0.5b-instruct-q4_k_m", causing a "Invalid model slug" error
 * when trying to download the model.
 *
 * @package WP_MCP_AI
 */

/**
 * Tests for embedded GGUF model slug sanitization fix.
 */
class Test_Embedded_Model_Slug_Sanitization extends WP_UnitTestCase {

	/**
	 * Ensure the embedded client class is loaded.
	 */
	public function setUp(): void {
		parent::setUp();

		if ( ! class_exists( 'WP_MCP_AI_Embedded_Client' ) ) {
			require_once WP_MCP_AI_PATH . 'includes/class-wp-mcp-ai-embedded-client.php';
		}
	}

	/**
	 * Confirm that sanitize_key() destroys model slugs containing dots.
	 *
	 * This documents the original bug so the regression is clearly visible.
	 */
	public function test_sanitize_key_strips_dots_from_slug() {
		$this->assertSame(
			'qwen2-05b-instruct-q4_k_m',
			sanitize_key( 'qwen2-0.5b-instruct-q4_k_m' ),
			'sanitize_key() must strip dots — this confirms the root cause of the bug'
		);

		$this->assertSame(
			'granite-31-2b-instruct-q4_k_m',
			sanitize_key( 'granite-3.1-2b-instruct-q4_k_m' ),
			'sanitize_key() also strips dots from the granite slug'
		);
	}

	/**
	 * All three GGUF model slugs must survive the new sanitization logic
	 * (preg_replace) unchanged — dots must be preserved.
	 */
	public function test_custom_sanitization_preserves_dots_in_gguf_slugs() {
		$slugs = array(
			'qwen2-0.5b-instruct-q4_k_m',
			'granite-3.1-2b-instruct-q4_k_m',
			'phi-3-mini-4k-instruct-q4',
		);

		foreach ( $slugs as $slug ) {
			$sanitized = preg_replace( '/[^a-z0-9._-]/', '', strtolower( $slug ) );
			$this->assertSame(
				$slug,
				$sanitized,
				"Slug '{$slug}' must be unchanged after the new sanitization"
			);
		}
	}

	/**
	 * The new sanitization must still strip genuinely dangerous characters
	 * (spaces, slashes, shell metacharacters, etc.).
	 */
	public function test_gguf_slug_sanitization_strips_unsafe_characters() {
		$cases = array(
			'../etc/passwd'         => 'etcpasswd',
			'model; rm -rf /'       => 'model-rm-rf-',
			'model<script>'         => 'modelscript',
			'MODEL_NAME'            => 'model_name',  // uppercased → lowercased.
			'model slug with space' => 'modelslugwithspace',
		);

		foreach ( $cases as $input => $expected ) {
			$sanitized = preg_replace( '/[^a-z0-9._-]/', '', strtolower( $input ) );
			$this->assertSame(
				$expected,
				$sanitized,
				"Input '{$input}' should sanitize to '{$expected}'"
			);
		}
	}

	/**
	 * After the fix, download_model() must accept "qwen2-0.5b-instruct-q4_k_m"
	 * and fail with a download/network error rather than "Invalid model slug".
	 *
	 * We mock wp_remote_get to avoid a real HTTP call.
	 */
	public function test_download_model_accepts_dotted_slug() {
		$client = new WP_MCP_AI_Embedded_Client();

		// Intercept the HTTP request so the test runs offline.
		add_filter(
			'pre_http_request',
			static function () {
				return new WP_Error( 'http_request_failed', 'Mocked network failure' );
			}
		);

		$result = $client->download_model( 'qwen2-0.5b-instruct-q4_k_m' );

		remove_all_filters( 'pre_http_request' );

		// The error must NOT be "Invalid model slug" — the slug was accepted.
		$this->assertInstanceOf(
			'WP_Error',
			$result,
			'Expected a WP_Error (network failure), not a plain array'
		);
		$this->assertNotSame(
			'wp_mcp_ai_invalid_model',
			$result->get_error_code(),
			'Error must not be "Invalid model slug" — slug should pass validation'
		);
	}

	/**
	 * The slug that was being generated by the broken sanitize_key() path
	 * ("qwen2-05b-instruct-q4_k_m" — no dot) must NOT match any known model.
	 */
	public function test_broken_sanitize_key_slug_is_not_a_valid_model() {
		$client = new WP_MCP_AI_Embedded_Client();

		// This is what sanitize_key() used to produce.
		$broken_slug = 'qwen2-05b-instruct-q4_k_m';
		$available   = $client->get_available_models();

		$this->assertArrayNotHasKey(
			$broken_slug,
			$available,
			"The broken slug '{$broken_slug}' (dots stripped by sanitize_key) must not be a valid model key"
		);
	}

	/**
	 * All three documented GGUF model slugs must be present in get_available_models().
	 */
	public function test_all_gguf_model_slugs_are_registered() {
		$client    = new WP_MCP_AI_Embedded_Client();
		$available = $client->get_available_models();

		$expected_slugs = array(
			'qwen2-0.5b-instruct-q4_k_m',
			'granite-3.1-2b-instruct-q4_k_m',
			'phi-3-mini-4k-instruct-q4',
		);

		foreach ( $expected_slugs as $slug ) {
			$this->assertArrayHasKey(
				$slug,
				$available,
				"Model slug '{$slug}' must be registered in get_available_models()"
			);
		}
	}
}
