<?php
/**
 * Tool that performs semantic search across WordPress content using embeddings.
 *
 * @package WP_MCP_AI
 * @author    NV Digital Solutions
 * @copyright Copyright (c) 2025-2026 NV Digital Solutions
 * @license   GPL-3.0-or-later
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Performs semantic search across WordPress content using vector embeddings.
 *
 * Embeddings are generated by the shared embedding-provider abstraction
 * ({@see WP_MCP_AI_Vector_Context_Service}), so the tool works with OpenAI,
 * Gemini, Ollama, or DigitalOcean embeddings regardless of the assistant's
 * chat provider. When no embedding backend is configured the tool degrades
 * to a keyword search instead of failing.
 */
class WP_MCP_AI_Tool_Semantic_Content_Search implements WP_MCP_AI_Tool_Interface, WP_MCP_AI_Tool_Capability_Flags_Interface {
	use WP_MCP_AI_Tool_Chat_Response;

	/**
	 * Maximum posts to query for semantic search.
	 *
	 * @var int
	 */
	const MAX_POSTS_TO_QUERY = 1000;

	/**
	 * {@inheritdoc}
	 */
	public function get_slug() {
		return 'semantic_content_search';
	}

	/**
	 * {@inheritdoc}
	 */
	public function get_name() {
		return __( 'Semantic Content Search', 'mcp-ai-wpoos' );
	}

	/**
	 * {@inheritdoc}
	 */
	public function get_description() {
		return __( 'Performs semantic search across WordPress content and health records using vector embeddings. Embeddings are generated by the configured embedding provider (OpenAI, Gemini, Ollama, or DigitalOcean — independent of the assistant\'s chat provider). Falls back to keyword search when no embedding provider is configured. Use this to find similar posts/pages, vital signs records, or content from a knowledge base.', 'mcp-ai-wpoos' );
	}

	/**
	 * {@inheritdoc}
	 */
	public function get_parameters_schema() {
		return array(
			'type'                 => 'object',
			'properties'           => array(
				'query'           => array(
					'type'        => 'string',
					'description' => __( 'Search query text to find semantically similar content.', 'mcp-ai-wpoos' ),
				),
				'vector_store_id' => array(
					'type'        => 'string',
					'description' => __( 'Optional OpenAI vector store ID to search. When provided (or configured on the assistant), the tool searches the vector store in addition to local WordPress content.', 'mcp-ai-wpoos' ),
				),
				'post_types'      => array(
					'type'        => 'array',
					'items'       => array(
						'type' => 'string',
					),
					'description' => __( 'Array of post types to search. Defaults to ["post", "page"].', 'mcp-ai-wpoos' ),
					'default'     => array( 'post', 'page' ),
				),
				'limit'           => array(
					'type'        => 'integer',
					'description' => __( 'Maximum number of results to return.', 'mcp-ai-wpoos' ),
					'default'     => 10,
					'minimum'     => 1,
					'maximum'     => 100,
				),
				'threshold'       => array(
					'type'        => 'number',
					'description' => __( 'Minimum similarity score threshold (0-1). Higher values return more similar results. Applies to semantic results only.', 'mcp-ai-wpoos' ),
					'default'     => 0.7,
					'minimum'     => 0,
					'maximum'     => 1,
				),
				'include_meta'    => array(
					'type'        => 'boolean',
					'description' => __( 'Include post metadata in results.', 'mcp-ai-wpoos' ),
					'default'     => false,
				),
			),
			'required'             => array( 'query' ),
			'additionalProperties' => false,
		);
	}

	/**
	 * {@inheritdoc}
	 */
	public function get_required_capability() {
		return 'edit_posts';
	}

	/**
	 * Execute the tool.
	 *
	 * @param array $arguments Tool arguments.
	 * @param array $context   Execution context including user_id and assistant_config.
	 * @return array|WP_Error Tool results or error.
	 */
	public function execute( array $arguments = array(), array $context = array() ) {
		$user_id = isset( $context['user_id'] ) ? absint( $context['user_id'] ) : get_current_user_id();

		// Check permissions.
		if ( ! $user_id || ! user_can( $user_id, 'read' ) ) {
			return new WP_Error(
				'wp_mcp_ai_forbidden',
				__( 'You do not have permission to perform semantic search.', 'mcp-ai-wpoos' )
			);
		}

		if ( is_multisite() && ! is_user_member_of_blog( $user_id, get_current_blog_id() ) ) {
			return new WP_Error( 'wp_mcp_ai_wrong_site', __( 'You do not have access to this site.', 'mcp-ai-wpoos' ) );
		}
		// Validate query.
		if ( ! isset( $arguments['query'] ) || empty( $arguments['query'] ) ) {
			return new WP_Error(
				'wp_mcp_ai_missing_query',
				__( 'Search query is required.', 'mcp-ai-wpoos' )
			);
		}

		$query        = sanitize_text_field( $arguments['query'] );
		$post_types   = isset( $arguments['post_types'] ) && is_array( $arguments['post_types'] ) ? array_map( 'sanitize_text_field', $arguments['post_types'] ) : array( 'post', 'page' );
		$limit        = isset( $arguments['limit'] ) ? absint( $arguments['limit'] ) : 10;
		$threshold    = isset( $arguments['threshold'] ) ? floatval( $arguments['threshold'] ) : 0.7;
		$include_meta = isset( $arguments['include_meta'] ) ? (bool) $arguments['include_meta'] : false;

		// Resolve vector store ID: explicit argument > assistant context configuration.
		$vector_store_id = '';
		if ( ! empty( $arguments['vector_store_id'] ) ) {
			$vector_store_id = sanitize_text_field( $arguments['vector_store_id'] );
		} elseif ( ! empty( $context['assistant_config']['vector_store_id'] ) ) {
			$vector_store_id = sanitize_text_field( $context['assistant_config']['vector_store_id'] );
		}

		// Ensure limit is within bounds.
		$limit = max( 1, min( 100, $limit ) );

		// Ensure threshold is within bounds.
		$threshold = max( 0.0, min( 1.0, $threshold ) );

		// The assistant's chat provider is only a *preference* for the embedding
		// backend (Gemini-backed assistants prefer Gemini embeddings); the
		// authoritative provider resolution happens in the vector context service.
		$assistant_provider = isset( $context['assistant_config']['provider'] ) ? strtolower( sanitize_key( $context['assistant_config']['provider'] ) ) : '';
		$results            = array();
		$vector_results     = array();
		$vector_store_state = 'not_requested';

		// Search the OpenAI vector store when one is configured.
		// Vector store search is always OpenAI-specific; a configured OpenAI client is used regardless of the chat provider.
		if ( ! empty( $vector_store_id ) ) {
			$openai_client = new WP_MCP_AI_OpenAI_Client();
			$vs_response   = $openai_client->search_vector_store(
				$vector_store_id,
				$query,
				array( 'max_num_results' => $limit )
			);

			if ( ! is_wp_error( $vs_response ) && ! empty( $vs_response['data'] ) ) {
				$vector_store_state = 'searched';
				foreach ( $vs_response['data'] as $item ) {
					$content_text = '';
					if ( ! empty( $item['content'] ) && is_array( $item['content'] ) ) {
						foreach ( $item['content'] as $chunk ) {
							if ( isset( $chunk['text'] ) ) {
								$content_text .= $chunk['text'] . ' ';
							}
						}
						$content_text = trim( $content_text );
					}

					$vector_results[] = array(
						'source'           => 'vector_store',
						'vector_store_id'  => $vector_store_id,
						'file_id'          => isset( $item['file_id'] ) ? sanitize_text_field( $item['file_id'] ) : '',
						'filename'         => isset( $item['filename'] ) ? sanitize_text_field( $item['filename'] ) : '',
						'excerpt'          => $content_text,
						'similarity_score' => isset( $item['score'] ) ? round( floatval( $item['score'] ), 4 ) : 0.0,
					);
				}
			} else {
				// A missing OpenAI key (or any vector-store failure) must not kill
				// local search — record the state and continue.
				$vector_store_state = 'skipped';
			}
		}

		// Generate embedding for the search query using the configured embedding provider.
		$embedding_data = $this->generate_query_embedding( $query, $assistant_provider );

		if ( is_wp_error( $embedding_data ) ) {
			// If embedding fails but we have vector store results, return those
			// with a warning so the agent still gets value.
			if ( ! empty( $vector_results ) ) {
				$summary_text = sprintf(
					/* translators: 1: number of results, 2: search query */
					__( 'Found %1$d result(s) in the vector store for "%2$s". Local WordPress content search was unavailable.', 'mcp-ai-wpoos' ),
					count( $vector_results ),
					$query
				);

				return array(
					'success'                  => true,
					'results'                  => array_slice( $vector_results, 0, $limit ),
					'total_found'              => count( $vector_results ),
					'query'                    => $query,
					'query_embedding_model'    => '',
					'query_embedding_provider' => '',
					'threshold'                => $threshold,
					'vector_store_id'          => $vector_store_id,
					'vector_store_search'      => $vector_store_state,
					'warning'                  => $embedding_data->get_error_message(),
					'message'                  => $summary_text,
					'summary'                  => $summary_text,
				);
			}

			// Graceful degradation: fall back to keyword search rather than
			// failing the whole tool (best practice: retrieval degradation).
			if ( $this->is_keyword_fallback_enabled() ) {
				return $this->run_keyword_search( $query, $post_types, $limit, $vector_store_id, $vector_store_state, $embedding_data->get_error_message(), $include_meta );
			}

			return $embedding_data;
		}

		$query_embedding    = $embedding_data['embedding'];
		$embedding_model    = $embedding_data['model'];
		$embedding_provider = $embedding_data['provider_id'];

		if ( empty( $query_embedding ) ) {
			return new WP_Error(
				'wp_mcp_ai_embedding_failed',
				__( 'Failed to generate query embedding.', 'mcp-ai-wpoos' )
			);
		}

		$query_dimensions = count( $query_embedding );

		// Query posts with stored embeddings.
		$args = array(
			'post_type'      => $post_types,
			'post_status'    => 'publish',
			'posts_per_page' => self::MAX_POSTS_TO_QUERY,
			'meta_key'       => '_wp_mcp_ai_embeddings', // phpcs:ignore WordPress.DB.SlowDBQuery.slow_db_query_meta_key -- Meta key lookup required for embedding index retrieval; performance trade-off accepted.
			'meta_query'     => array( // phpcs:ignore WordPress.DB.SlowDBQuery.slow_db_query_meta_query -- Meta query required for embedding/semantic search functionality; performance trade-off accepted.
				array(
					'key'     => '_wp_mcp_ai_embeddings',
					'compare' => 'EXISTS',
				),
			),
		);

		$posts_query = new WP_Query( $args );

		$embeddings_checked         = 0;
		$skipped_dimension_mismatch = 0;

		if ( $posts_query->have_posts() ) {
			while ( $posts_query->have_posts() ) {
				$posts_query->the_post();
				$post_id = get_the_ID();

				// Get stored embeddings.
				$stored_embeddings = get_post_meta( $post_id, '_wp_mcp_ai_embeddings', true );

				if ( empty( $stored_embeddings ) || ! isset( $stored_embeddings['embeddings'][0]['embedding'] ) ) {
					continue;
				}

				$post_embedding = $stored_embeddings['embeddings'][0]['embedding'];

				if ( ! is_array( $post_embedding ) || empty( $post_embedding ) ) {
					continue;
				}

				// Dimension hygiene: cosine similarity is undefined between
				// vectors from different models. Skip mismatched rows and
				// report the count so agents can see why results are sparse.
				if ( count( $post_embedding ) !== $query_dimensions ) {
					++$skipped_dimension_mismatch;
					continue;
				}

				++$embeddings_checked;

				// Calculate cosine similarity.
				$similarity = $this->calculate_cosine_similarity( $query_embedding, $post_embedding );

				// Filter by threshold.
				if ( $similarity < $threshold ) {
					continue;
				}

				$result = array(
					'source'           => 'wordpress',
					'post_id'          => $post_id,
					'title'            => get_the_title(),
					'excerpt'          => get_the_excerpt(),
					'similarity_score' => round( $similarity, 4 ),
					'permalink'        => get_permalink(),
					'post_type'        => get_post_type(),
				);

				if ( $include_meta ) {
					$result['meta'] = array(
						'author'          => get_the_author(),
						'date'            => get_the_date( 'Y-m-d H:i:s' ),
						'modified'        => get_the_modified_date( 'Y-m-d H:i:s' ),
						'embedding_model' => isset( $stored_embeddings['model'] ) ? sanitize_text_field( $stored_embeddings['model'] ) : '',
					);
				}

				$results[] = $result;
			}

			wp_reset_postdata();
		}

		// Merge vector store and local WordPress results.
		$all_results = array_merge( $vector_results, $results );

		// Also search the vitals embedding index so that queries about vital signs
		// and kidney health metrics return relevant records even though they are not
		// stored as WordPress posts.
		$vitals_results = $this->search_vitals_embeddings( $query_embedding, $threshold, $limit );
		$all_results    = array_merge( $all_results, $vitals_results );

		// Sort combined results by similarity score (descending). Keyword and
		// vitals entries always carry a numeric score, so the comparator is safe.
		usort(
			$all_results,
			function ( $a, $b ) {
				$score_a = isset( $a['similarity_score'] ) ? floatval( $a['similarity_score'] ) : 0.0;
				$score_b = isset( $b['similarity_score'] ) ? floatval( $b['similarity_score'] ) : 0.0;
				return $score_b <=> $score_a;
			}
		);

		// Limit results.
		$all_results = array_slice( $all_results, 0, $limit );

		$summary_text = sprintf(
			/* translators: 1: number of results, 2: search query */
			__( 'Found %1$d semantically similar results for "%2$s".', 'mcp-ai-wpoos' ),
			count( $all_results ),
			$query
		);

		return array(
			'success'                    => true,
			'results'                    => $all_results,
			'total_found'                => count( $all_results ),
			'query'                      => $query,
			'query_embedding_model'      => $embedding_model,
			'query_embedding_provider'   => $embedding_provider,
			'threshold'                  => $threshold,
			'vector_store_id'            => $vector_store_id,
			'vector_store_search'        => $vector_store_state,
			'embeddings_checked'         => $embeddings_checked,
			'skipped_dimension_mismatch' => $skipped_dimension_mismatch,
			'message'                    => $summary_text,
			'summary'                    => $summary_text,
		);
	}

	/**
	 * Whether keyword-search degradation is enabled.
	 *
	 * @return bool True when the tool may fall back to keyword search.
	 */
	private function is_keyword_fallback_enabled() {
		/**
		 * Filter whether semantic_content_search falls back to keyword search
		 * when no embedding provider is available. Sites that prefer a hard
		 * failure can disable the fallback here.
		 *
		 * @since 1.2.0
		 *
		 * @param bool $enabled Default true.
		 */
		return (bool) apply_filters( 'wp_mcp_ai_semantic_search_keyword_fallback', true );
	}

	/**
	 * Run a keyword search as a degraded fallback for semantic search.
	 *
	 * Mirrors the graceful-degradation pattern used by the `search_content`
	 * tool: retrieval should fall back to keyword matching rather than fail
	 * outright when embeddings are unavailable.
	 *
	 * @param string $query              Search query.
	 * @param array  $post_types         Post types to search.
	 * @param int    $limit              Maximum results.
	 * @param string $vector_store_id    Configured vector store ID (context only).
	 * @param string $vector_store_state Vector store search state (context only).
	 * @param string $warning            Human-readable reason semantic search was unavailable.
	 * @param bool   $include_meta       Whether to include post metadata.
	 * @return array Success envelope with keyword results and fallback flags.
	 */
	private function run_keyword_search( $query, $post_types, $limit, $vector_store_id, $vector_store_state, $warning, $include_meta ) {
		$keyword_args = array(
			'post_type'      => $post_types,
			'post_status'    => 'publish',
			'posts_per_page' => $limit,
			's'              => $query,
		);

		$keyword_query = new WP_Query( $keyword_args );
		$results       = array();

		if ( $keyword_query->have_posts() ) {
			while ( $keyword_query->have_posts() ) {
				$keyword_query->the_post();
				$post_id = get_the_ID();

				$result = array(
					'source'           => 'wordpress_keyword',
					'post_id'          => $post_id,
					'title'            => get_the_title(),
					'excerpt'          => get_the_excerpt(),
					'similarity_score' => null,
					'permalink'        => get_permalink(),
					'post_type'        => get_post_type(),
				);

				if ( $include_meta ) {
					$result['meta'] = array(
						'author'   => get_the_author(),
						'date'     => get_the_date( 'Y-m-d H:i:s' ),
						'modified' => get_the_modified_date( 'Y-m-d H:i:s' ),
					);
				}

				$results[] = $result;
			}

			wp_reset_postdata();
		}

		$summary_text = sprintf(
			/* translators: 1: number of results, 2: search query */
			__( 'Found %1$d keyword result(s) for "%2$s" (semantic search unavailable).', 'mcp-ai-wpoos' ),
			count( $results ),
			$query
		);

		return array(
			'success'                  => true,
			'fallback_mode'            => 'keyword',
			'semantic_search_enabled'  => false,
			'results'                  => $results,
			'total_found'              => count( $results ),
			'query'                    => $query,
			'query_embedding_model'    => '',
			'query_embedding_provider' => '',
			'threshold'                => 0.0,
			'vector_store_id'          => $vector_store_id,
			'vector_store_search'      => $vector_store_state,
			'warning'                  => $warning,
			'message'                  => $summary_text,
			'summary'                  => $summary_text,
		);
	}

	/**
	 * Search the vitals embedding index for entries semantically similar to the
	 * given query vector.
	 *
	 * This is the counterpart of {@see WP_MCP_AI_Tool_Log_Vital_Signs::store_vitals_embedding()}.
	 * It reads the shared `wp_mcp_ai_vitals_embed_index` option and returns the
	 * entries whose embedding is closest to $query_embedding.
	 *
	 * @param array $query_embedding Query embedding vector.
	 * @param float $threshold       Minimum cosine similarity (0–1).
	 * @param int   $limit           Maximum results to return.
	 * @return array Array of result items (source = 'vitals').
	 */
	private function search_vitals_embeddings( array $query_embedding, $threshold, $limit ) {
		$index = get_option( 'wp_mcp_ai_vitals_embed_index', array() );

		if ( empty( $index ) ) {
			return array();
		}

		$results = array();

		foreach ( $index as $entry_id => $entry ) {
			if ( empty( $entry['embedding'] ) || ! is_array( $entry['embedding'] ) ) {
				continue;
			}

			// Dimension hygiene: skip vectors produced by a different model.
			if ( count( $entry['embedding'] ) !== count( $query_embedding ) ) {
				continue;
			}

			$similarity = $this->calculate_cosine_similarity( $query_embedding, $entry['embedding'] );

			if ( $similarity < $threshold ) {
				continue;
			}

			$results[] = array(
				'source'           => 'vitals',
				'entry_id'         => sanitize_text_field( $entry_id ),
				'member_id'        => isset( $entry['member_id'] ) ? absint( $entry['member_id'] ) : 0,
				'date'             => isset( $entry['date'] ) ? sanitize_text_field( $entry['date'] ) : '',
				'excerpt'          => isset( $entry['text'] ) ? wp_trim_words( $entry['text'], 30 ) : '',
				'similarity_score' => round( $similarity, 4 ),
			);
		}

		// Sort by similarity (descending) and limit.
		usort(
			$results,
			function ( $a, $b ) {
				return $b['similarity_score'] <=> $a['similarity_score'];
			}
		);

		return array_slice( $results, 0, $limit );
	}

	/**
	 * Generate a query embedding using the shared embedding-provider abstraction.
	 *
	 * Gemini-backed assistants prefer Gemini embeddings; every other case is
	 * resolved by {@see WP_MCP_AI_Vector_Context_Service::get_embedding_provider()},
	 * which honours the explicit `embedding_provider` setting, the
	 * `wp_mcp_ai_embedding_provider` filter, and the auto-detect chain
	 * (OpenAI → Ollama → Gemini → DigitalOcean). The assistant's chat provider
	 * (e.g. DeepSeek) no longer dictates the embedding backend.
	 *
	 * @param string $query    Search query text.
	 * @param string $provider Lowercase AI provider name from assistant context (e.g. 'openai', 'gemini', 'deepseek').
	 * @return array|WP_Error Array with 'embedding' (float[]), 'model' (string) and 'provider_id' (string), or WP_Error on failure.
	 */
	private function generate_query_embedding( $query, $provider ) {
		// Delegate to the shared embedding-provider resolution so the tool
		// works with OpenAI, Ollama, Gemini, or DigitalOcean regardless of the
		// assistant's chat provider.
		if ( class_exists( 'WP_MCP_AI_Vector_Context_Service' ) ) {
			$vector_service = WP_MCP_AI_Vector_Context_Service::get_instance();

			// Resolving through the service first also ensures the provider
			// classes (including Gemini) are loaded on demand.
			$embedding_provider = $vector_service->get_embedding_provider();

			// Assistant-provider preference: Gemini-backed assistants prefer
			// Gemini embeddings, mirroring the historical behaviour.
			if ( in_array( $provider, array( 'gemini', 'google' ), true )
				&& class_exists( 'WP_MCP_AI_Embedding_Provider_Gemini' ) ) {
				$gemini_provider = new WP_MCP_AI_Embedding_Provider_Gemini();

				if ( $gemini_provider->is_available() ) {
					$embedding = $gemini_provider->embed( $query );

					if ( ! is_wp_error( $embedding ) && ! empty( $embedding ) ) {
						return array(
							'embedding'   => $embedding,
							'model'       => $gemini_provider->get_model(),
							'provider_id' => $gemini_provider->get_id(),
						);
					}
				}

				// Fall through to the resolved provider when Gemini is
				// unavailable or its embedding call fails.
			}

			if ( ! is_wp_error( $embedding_provider ) ) {
				$embedding = $embedding_provider->embed( $query );

				if ( is_wp_error( $embedding ) ) {
					return $embedding;
				}

				if ( empty( $embedding ) ) {
					return new WP_Error(
						'wp_mcp_ai_embedding_failed',
						__( 'Failed to generate query embedding.', 'mcp-ai-wpoos' )
					);
				}

				return array(
					'embedding'   => $embedding,
					'model'       => $embedding_provider->get_model(),
					'provider_id' => $embedding_provider->get_id(),
				);
			}

			return new WP_Error(
				'wp_mcp_ai_no_embedding_provider',
				__( 'No embedding provider is configured, so semantic search is unavailable.', 'mcp-ai-wpoos' ),
				array(
					'status'  => 400,
					'actions' => array(
						'configure_openai_key'   => __( 'Add an OpenAI API key in the NV oOS settings.', 'mcp-ai-wpoos' ),
						'configure_gemini_key'   => __( 'Add a Gemini API key in the NV oOS settings.', 'mcp-ai-wpoos' ),
						'configure_ollama'       => __( 'Configure an Ollama endpoint URL in the NV oOS settings.', 'mcp-ai-wpoos' ),
						'configure_digitalocean' => __( 'Add a DigitalOcean API key in the NV oOS settings.', 'mcp-ai-wpoos' ),
						'set_embedding_provider' => __( 'Set the embedding_provider setting to a configured backend.', 'mcp-ai-wpoos' ),
					),
				)
			);
		}

		// Fallback for environments where the vector service is unavailable:
		// retain the historical OpenAI path with an actionable error.
		$openai_client   = new WP_MCP_AI_OpenAI_Client();
		$openai_response = $openai_client->create_embeddings( $query );

		if ( is_wp_error( $openai_response ) ) {
			return $openai_response;
		}

		if ( ! isset( $openai_response['data'][0]['embedding'] ) ) {
			return new WP_Error(
				'wp_mcp_ai_embedding_failed',
				__( 'Failed to generate query embedding.', 'mcp-ai-wpoos' )
			);
		}

		return array(
			'embedding'   => $openai_response['data'][0]['embedding'],
			'model'       => isset( $openai_response['model'] ) ? $openai_response['model'] : 'text-embedding-3-small',
			'provider_id' => 'openai',
		);
	}

	/**
	 * Calculate cosine similarity between two vectors.
	 *
	 * @param array $vector_a First vector.
	 * @param array $vector_b Second vector.
	 * @return float Cosine similarity score (0-1).
	 */
	private function calculate_cosine_similarity( $vector_a, $vector_b ) {
		if ( count( $vector_a ) !== count( $vector_b ) ) {
			return 0.0;
		}

		$dot_product = 0.0;
		$magnitude_a = 0.0;
		$magnitude_b = 0.0;
		$vector_size = count( $vector_a );

		for ( $i = 0; $i < $vector_size; $i++ ) {
			$dot_product += $vector_a[ $i ] * $vector_b[ $i ];
			$magnitude_a += $vector_a[ $i ] * $vector_a[ $i ];
			$magnitude_b += $vector_b[ $i ] * $vector_b[ $i ];
		}

		$magnitude_a = sqrt( $magnitude_a );
		$magnitude_b = sqrt( $magnitude_b );

		if ( 0.0 === $magnitude_a || 0.0 === $magnitude_b ) {
			return 0.0;
		}

		return $dot_product / ( $magnitude_a * $magnitude_b );
	}


	/**
	 * Get extended tool definition including toolkit metadata.
	 *
	 * @since 1.1.0
	 *
	 * @return array Tool definition with metadata.
	 */
	public function get_definition() {

		return array(

			'name'                  => $this->get_name(),

			'description'           => $this->get_description(),

			'toolkit'               => 'content_publishing',

			'pattern_compatibility' => array( 'orchestrator', 'peer_to_peer' ),

			'profession_tags'       => array( 'content_strategist', 'researcher' ),

			'risk_level'            => 'info',

		);
	}


	/**
	 * {@inheritdoc}
	 */
	public function get_capability_flags() {
		return array(
			'read-only',            // Only reads data, does not modify state.
			'external-api',         // Makes external API calls (OpenAI/Gemini/Ollama/DigitalOcean) for query embedding.
			'requires-capability',  // Requires 'read' capability.
		);
	}
}
