<?php
/**
 * Tools & Admin Controller for REST API
 *
 * Handles tools, file downloads, and admin-related endpoints including
 * tool listing, tool execution, file downloads, and cron status.
 *
 * @package WP_MCP_AI
 * @since 1.0.0
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Tools & Admin Controller Class
 *
 * Manages all tools and admin-related REST API endpoints:
 * - /tools (GET - list tools, POST - execute tool)
 * - /files/{file_id}/download (GET - file download)
 * - /cron-status (GET - cron job status for admin dashboard)
 */
class WP_MCP_AI_REST_Tools_Controller extends WP_MCP_AI_REST_Controller_Base {
	/**
	 * Reference to the main REST controller for shared functionality.
	 *
	 * @var WP_MCP_AI_REST
	 */
	private $main_controller;

	/**
	 * Constructor.
	 *
	 * @param WP_MCP_AI_REST                    $main_controller Main REST controller.
	 * @param WP_MCP_AI_REST_Authenticator|null $authenticator   Authentication handler (optional, for DI).
	 * @param WP_MCP_AI_REST_Validator|null     $validator       Request validator (optional, for DI).
	 */
	public function __construct( $main_controller = null, $authenticator = null, $validator = null ) {
		parent::__construct( $authenticator, $validator );
		$this->main_controller = $main_controller;
	}

	/**
	 * Register tools and admin routes.
	 *
	 * Registers REST API endpoints for tool management and administration:
	 * - GET /tools: List available tools for an assistant or all tools
	 * - POST /tools: Execute a specific tool with provided arguments
	 * - GET /files/{file_id}/download: Download files generated by tools
	 * - GET /cron-status: Get status of background cron jobs
	 *
	 * Tool execution endpoint supports:
	 * - Direct tool invocation with validation
	 * - Assistant context for scoped tool access
	 * - Capability checking (required_capability per tool)
	 * - Tool output sanitization and budget constraints
	 *
	 * File download endpoint provides:
	 * - Secure file access with permission checks
	 * - Support for both OpenAI file IDs and WordPress attachment IDs
	 * - Custom download filenames and Content-Disposition headers
	 * - Query string nonce support for in-browser file previews
	 *
	 * Cron status endpoint returns:
	 * - Recent job status summaries for authenticated users
	 * - Job counts by status (pending, running, completed, failed)
	 * - Admin-only access to site-wide cron statistics
	 *
	 * @since 1.0.0
	 */
	public function register_routes() {
		// /tools - Tool listing and execution.
		register_rest_route(
			self::REST_NAMESPACE,
			'/tools',
			array(
				array(
					'methods'             => WP_REST_Server::READABLE,
					'permission_callback' => array( $this, 'permissions_check' ),
					'callback'            => array( $this, 'handle_tools_list' ),
					'args'                => array(
						'assistant_id' => array(
							'description'       => __( 'ID of the assistant to list tools for. Returns all tools if omitted.', 'wp-mcp-ai' ),
							'type'              => 'integer',
							'required'          => false,
							'sanitize_callback' => 'absint',
						),
					),
				),
				array(
					'methods'             => WP_REST_Server::CREATABLE,
					'permission_callback' => array( $this, 'permissions_check' ),
					'callback'            => array( $this, 'handle_tool_request' ),
					'args'                => array(
						'assistant_id' => array(
							'description'       => __( 'ID of the assistant context for tool execution.', 'wp-mcp-ai' ),
							'type'              => 'integer',
							'required'          => false,
							'sanitize_callback' => 'absint',
						),
						'tool'         => array(
							'description'       => __( 'Slug of the tool to execute.', 'wp-mcp-ai' ),
							'type'              => 'string',
							'required'          => true,
							'sanitize_callback' => 'sanitize_key',
						),
						'arguments'    => array(
							'description' => __( 'Arguments to pass to the tool execution.', 'wp-mcp-ai' ),
							'type'        => 'object',
							'required'    => false,
							'default'     => array(),
						),
					),
				),
			),
			true
		);

		// /files/{file_id}/download - File download with permission checks.
		register_rest_route(
			self::REST_NAMESPACE,
			'/files/(?P<file_id>[^/]+)/download',
			array(
				array(
					'methods'             => WP_REST_Server::READABLE,
					'permission_callback' => array( $this, 'download_file_permissions_check' ),
					'callback'            => array( $this, 'handle_file_download' ),
					'args'                => array(
						'assistant_id'  => array(
							'description'       => __( 'ID of the assistant context for file access.', 'wp-mcp-ai' ),
							'type'              => 'integer',
							'required'          => false,
							'sanitize_callback' => 'absint',
						),
						'file_id'       => array(
							'description'       => __( 'ID or identifier of the file to download.', 'wp-mcp-ai' ),
							'type'              => 'string',
							'required'          => true,
							'sanitize_callback' => 'sanitize_text_field',
						),
						'download_name' => array(
							'description'       => __( 'Optional custom filename for the download.', 'wp-mcp-ai' ),
							'type'              => 'string',
							'required'          => false,
							'sanitize_callback' => 'sanitize_file_name',
						),
						'disposition'   => array(
							'description'       => __( 'Content-Disposition header value (attachment or inline).', 'wp-mcp-ai' ),
							'type'              => 'string',
							'required'          => false,
							'default'           => 'attachment',
							'enum'              => array( 'attachment', 'inline' ),
							'sanitize_callback' => 'sanitize_key',
						),
					),
				),
			),
			true
		);

		// /cron-status - Lightweight cron job status for admin dashboard and chat widgets.
		register_rest_route(
			self::REST_NAMESPACE,
			'/cron-status',
			array(
				array(
					'methods'             => WP_REST_Server::READABLE,
					'permission_callback' => array( $this, 'permissions_check_cron_status' ),
					'callback'            => array( $this, 'handle_cron_status_request' ),
					'args'                => array(
						'assistant_id' => array(
							'description'       => __( 'Filter jobs by assistant ID for multi-widget isolation.', 'wp-mcp-ai' ),
							'type'              => 'integer',
							'required'          => false,
							'sanitize_callback' => 'absint',
						),
						'limit'        => array(
							'description'       => __( 'Maximum number of jobs to return.', 'wp-mcp-ai' ),
							'type'              => 'integer',
							'required'          => false,
							'default'           => 10,
							'sanitize_callback' => 'absint',
							'minimum'           => 1,
							'maximum'           => 50,
						),
						'context'      => array(
							'description'       => __( 'Context for filtering jobs: "chat" excludes internal async jobs, "admin" shows all.', 'wp-mcp-ai' ),
							'type'              => 'string',
							'required'          => false,
							'default'           => 'admin',
							'enum'              => array( 'chat', 'admin' ),
							'sanitize_callback' => 'sanitize_key',
						),
					),
				),
			),
			true
		);

		// /cron-status/(?P<job_id>[a-zA-Z0-9_.]+) - Get details for a specific cron job.
		// Updated regex to support dots in job IDs (e.g., veo_69203b5b2388f5.11575461 from uniqid).
		register_rest_route(
			self::REST_NAMESPACE,
			'/cron-status/(?P<job_id>[a-zA-Z0-9_.]+)',
			array(
				array(
					'methods'             => WP_REST_Server::READABLE,
					'permission_callback' => array( $this, 'permissions_check_cron_status' ),
					'callback'            => array( $this, 'handle_cron_job_details_request' ),
					'args'                => array(
						'job_id' => array(
							'description'       => __( 'Cron job identifier.', 'wp-mcp-ai' ),
							'type'              => 'string',
							'required'          => true,
							'sanitize_callback' => array( $this, 'sanitize_job_id' ),
						),
						'stream' => array(
							'description' => __( 'Enable Server-Sent Events streaming for real-time updates.', 'wp-mcp-ai' ),
							'type'        => 'boolean',
							'required'    => false,
							'default'     => false,
						),
					),
				),
			),
			true
		);

		// /job-notifications - Get pending job completion notifications for chat client.
		register_rest_route(
			self::REST_NAMESPACE,
			'/job-notifications',
			array(
				array(
					'methods'             => WP_REST_Server::READABLE,
					'permission_callback' => array( $this, 'permissions_check' ),
					'callback'            => array( $this, 'handle_job_notifications_request' ),
					'args'                => array(
						'assistant_id' => array(
							'description'       => __( 'Assistant ID to filter notifications.', 'wp-mcp-ai' ),
							'type'              => 'integer',
							'required'          => true,
							'validate_callback' => function( $param ) {
								return is_numeric( $param ) && $param > 0;
							},
						),
						'clear' => array(
							'description' => __( 'Whether to clear notifications after retrieval.', 'wp-mcp-ai' ),
							'type'        => 'boolean',
							'required'    => false,
							'default'     => true,
						),
					),
				),
			),
			true
		);

		// /job-notifications/stream - SSE stream for real-time notifications and job counts.
		register_rest_route(
			self::REST_NAMESPACE,
			'/job-notifications/stream',
			array(
				array(
					'methods'             => WP_REST_Server::READABLE,
					'permission_callback' => array( $this, 'permissions_check' ),
					'callback'            => array( $this, 'handle_job_notifications_stream' ),
					'args'                => array(
						'assistant_id'  => array(
							'description'       => __( 'Assistant ID to stream notifications for.', 'wp-mcp-ai' ),
							'type'              => 'integer',
							'required'          => true,
							'validate_callback' => function( $param ) {
								return is_numeric( $param ) && $param > 0;
							},
						),
						'max_duration'  => array(
							'description' => __( 'Maximum duration in seconds to keep the stream open.', 'wp-mcp-ai' ),
							'type'        => 'integer',
							'minimum'     => 10,
							'maximum'     => 600,
							'default'     => 300,
						),
						'poll_interval' => array(
							'description' => __( 'Interval in seconds between status checks.', 'wp-mcp-ai' ),
							'type'        => 'integer',
							'minimum'     => 1,
							'maximum'     => 30,
							'default'     => 2,
						),
					),
				),
			),
			true
		);
	}

	/**
	 * General permission check for authenticated endpoints.
	 *
	 * @param WP_REST_Request $request REST request instance.
	 * @return bool|WP_Error
	 */
	public function permissions_check( WP_REST_Request $request ) {
		// Validate main controller is available.
		if ( null === $this->main_controller ) {
			return new WP_Error(
				'wp_mcp_ai_controller_not_initialized',
				__( 'REST controller not properly initialized.', 'wp-mcp-ai' ),
				array( 'status' => 500 )
			);
		}

		// Delegate to main controller.
		return $this->main_controller->permissions_check( $request );
	}

	/**
	 * Permission check for file download endpoint.
	 *
	 * Handles nonce parameter extraction before delegating to main permission check.
	 *
	 * @param WP_REST_Request $request REST request instance.
	 * @return bool|WP_Error
	 */
	public function download_file_permissions_check( WP_REST_Request $request ) {
		// Validate main controller is available.
		if ( null === $this->main_controller ) {
			return new WP_Error(
				'wp_mcp_ai_controller_not_initialized',
				__( 'REST controller not properly initialized.', 'wp-mcp-ai' ),
				array( 'status' => 500 )
			);
		}

		// Delegate to main controller.
		return $this->main_controller->download_file_permissions_check( $request );
	}

	/**
	 * Permission check for cron status endpoint.
	 *
	 * Supports mesh keys, bearer tokens, guest tokens, and WordPress nonces.
	 *
	 * @param WP_REST_Request $request REST request instance.
	 * @return bool|WP_Error
	 */
	public function permissions_check_cron_status( WP_REST_Request $request ) {
		// Validate main controller is available.
		if ( null === $this->main_controller ) {
			return new WP_Error(
				'wp_mcp_ai_controller_not_initialized',
				__( 'REST controller not properly initialized.', 'wp-mcp-ai' ),
				array( 'status' => 500 )
			);
		}

		// Delegate to main controller.
		return $this->main_controller->permissions_check_cron_status( $request );
	}

	/**
	 * Handle GET /tools request - List available tools.
	 *
	 * Delegates to main REST controller for now.
	 * Will be extracted in implementation phase.
	 *
	 * @param WP_REST_Request $request REST request object.
	 * @return WP_REST_Response|WP_Error Response object.
	 */
	public function handle_tools_list( WP_REST_Request $request ) {
		// Delegate to main controller.
		if ( $this->main_controller ) {
			return $this->main_controller->handle_tools_list( $request );
		}
		return $this->error( 'not_implemented', __( 'Tools list endpoint not yet fully extracted.', 'wp-mcp-ai' ), 501 );
	}

	/**
	 * Handle POST /tools request - Execute a tool.
	 *
	 * Delegates to main REST controller for now.
	 * Will be extracted in implementation phase.
	 *
	 * @param WP_REST_Request $request REST request object.
	 * @return WP_REST_Response|WP_Error Response object.
	 */
	public function handle_tool_request( WP_REST_Request $request ) {
		// Delegate to main controller.
		if ( $this->main_controller ) {
			return $this->main_controller->handle_tool_request( $request );
		}
		return $this->error( 'not_implemented', __( 'Tool execution endpoint not yet fully extracted.', 'wp-mcp-ai' ), 501 );
	}

	/**
	 * Handle GET /files/{file_id}/download request.
	 *
	 * Downloads a file from OpenAI and streams it to the client.
	 * Delegates to main REST controller for now.
	 * Will be extracted in implementation phase.
	 *
	 * @param WP_REST_Request $request REST request object.
	 * @return WP_REST_Response|WP_Error Response object.
	 */
	public function handle_file_download( WP_REST_Request $request ) {
		// Delegate to main controller.
		if ( $this->main_controller ) {
			return $this->main_controller->handle_file_download( $request );
		}
		return $this->error( 'not_implemented', __( 'File download endpoint not yet fully extracted.', 'wp-mcp-ai' ), 501 );
	}

	/**
	 * Handle GET /cron-status request.
	 *
	 * Returns lightweight cron job status information for the admin dashboard.
	 * Delegates to main REST controller for now.
	 * Will be extracted in implementation phase.
	 *
	 * @param WP_REST_Request $request REST request object.
	 * @return WP_REST_Response|WP_Error Response object.
	 */
	public function handle_cron_status_request( WP_REST_Request $request ) {
		// Delegate to main controller.
		if ( $this->main_controller ) {
			return $this->main_controller->handle_cron_status_request( $request );
		}
		return $this->error( 'not_implemented', __( 'Cron status endpoint not yet fully extracted.', 'wp-mcp-ai' ), 501 );
	}

	/**
	 * Handle GET /cron-status/{job_id} request.
	 *
	 * Returns detailed information about a specific cron job.
	 * Follows SOC by delegating to cron status service.
	 *
	 * @param WP_REST_Request $request REST request object.
	 * @return WP_REST_Response|WP_Error Response object.
	 */
	public function handle_cron_job_details_request( WP_REST_Request $request ) {
		// Delegate to main controller.
		if ( $this->main_controller ) {
			return $this->main_controller->handle_cron_job_details_request( $request );
		}
		return $this->error( 'not_implemented', __( 'Cron job details endpoint not yet fully extracted.', 'wp-mcp-ai' ), 501 );
	}

	/**
	 * Handle GET /job-notifications request.
	 *
	 * Retrieves pending job completion notifications for the current user and assistant.
	 * Notifications are stored when async jobs complete and cleared when retrieved.
	 *
	 * @param WP_REST_Request $request REST request instance.
	 * @return WP_REST_Response|WP_Error
	 */
	public function handle_job_notifications_request( WP_REST_Request $request ) {
		$assistant_id = absint( $request->get_param( 'assistant_id' ) );
		$clear        = (bool) $request->get_param( 'clear' );

		// Get current user ID.
		$user_id = get_current_user_id();

		// Get event dispatcher service.
		if ( ! class_exists( 'WP_MCP_AI_Event_Dispatcher_Service' ) ) {
			require_once WP_MCP_AI_PATH . 'includes/services/class-wp-mcp-ai-event-dispatcher-service.php';
		}

		$dispatcher = WP_MCP_AI_Event_Dispatcher_Service::get_instance();

		// Get pending notifications.
		$notifications = $dispatcher->get_pending_notifications( $user_id, $assistant_id, $clear );

		// Get job counts from cron status service to consolidate polling.
		// This eliminates the need for separate cron-status polling.
		$job_counts = array(
			'pending'   => 0,
			'running'   => 0,
			'completed' => 0,
			'failed'    => 0,
			'total'     => 0,
		);

		if ( $this->main_controller && method_exists( $this->main_controller, 'get_cron_status_service' ) ) {
			$cron_service = $this->main_controller->get_cron_status_service();
			if ( $cron_service && method_exists( $cron_service, 'get_status_counts' ) ) {
				$counts_data = $cron_service->get_status_counts( $user_id, $assistant_id, 'chat' );
				if ( is_array( $counts_data ) ) {
					$job_counts = $counts_data;
				}
			}
		}

		return rest_ensure_response(
			array(
				'notifications' => $notifications,
				'count'         => count( $notifications ),
				'job_counts'    => $job_counts,
			)
		);
	}

	/**
	 * Handle GET /job-notifications/stream request (SSE).
	 *
	 * Streams real-time job notifications and count updates via Server-Sent Events.
	 * Eliminates the need for polling in the chat client for real-time updates.
	 *
	 * @param WP_REST_Request $request REST request instance.
	 * @return void Exits after streaming.
	 */
	public function handle_job_notifications_stream( WP_REST_Request $request ) {
		$assistant_id  = absint( $request->get_param( 'assistant_id' ) );
		$max_duration  = absint( $request->get_param( 'max_duration' ) );
		$poll_interval = absint( $request->get_param( 'poll_interval' ) );

		// Get current user ID.
		$user_id = get_current_user_id();

		// Load SSE notification stream service.
		if ( ! class_exists( 'WP_MCP_AI_SSE_Notification_Stream' ) ) {
			require_once WP_MCP_AI_PATH . 'includes/services/class-wp-mcp-ai-sse-notification-stream.php';
		}

		// Stream notifications (this will exit).
		WP_MCP_AI_SSE_Notification_Stream::stream_notifications(
			$assistant_id,
			$user_id,
			$max_duration,
			$poll_interval
		);
	}

	/**
	 * Sanitize job ID parameter.
	 *
	 * Job IDs are generated using uniqid() with more_entropy=true, which produces
	 * IDs like 'veo_69203b5b2388f5.11575461'. This sanitization function preserves
	 * the dot character while blocking path traversal and other malicious input.
	 *
	 * @param string $job_id Job ID to sanitize.
	 * @return string Sanitized job ID.
	 */
	public function sanitize_job_id( $job_id ) {
		// Remove any characters that aren't alphanumeric, underscore, dot, or hyphen.
		$sanitized = preg_replace( '/[^a-zA-Z0-9_.\-]/', '', $job_id );

		// Remove path traversal attempts (consecutive dots).
		$sanitized = preg_replace( '/\.\.+/', '', $sanitized );

		return $sanitized;
	}
}
