<?php
/**
 * Embedding provider interface.
 *
 * Implementations supply text → vector embeddings to the
 * {@see WP_MCP_AI_Vector_Context_Service}. Allows the plugin to switch
 * between OpenAI (default), local Ollama, or any future backend.
 *
 * MemPalace-inspired Phase 3 enhancement.
 *
 * @package WP_MCP_AI
 * @since 1.1.0
 * @author    NV Digital Solutions
 * @copyright Copyright (c) 2025-2026 NV Digital Solutions
 * @license   GPL-3.0-or-later
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Contract for plug-in embedding providers.
 *
 * @since 1.1.0
 */
interface WP_MCP_AI_Embedding_Provider_Interface {
	/**
	 * Stable identifier for the provider (e.g. "openai", "ollama").
	 *
	 * Used in the embedding cache key so switching providers does not
	 * return vectors generated by a different backend.
	 *
	 * @return string
	 */
	public function get_id();

	/**
	 * Identifier of the embedding model the provider will use
	 * (e.g. "text-embedding-3-small", "nomic-embed-text").
	 *
	 * Included in the cache key so switching models invalidates cached vectors.
	 *
	 * @return string
	 */
	public function get_model();

	/**
	 * Whether the provider is configured and ready to be called.
	 *
	 * Implementations should return false (rather than throwing) when, e.g.,
	 * an API key or endpoint URL is missing. The vector service surfaces a
	 * structured WP_Error to callers in that case.
	 *
	 * @return bool
	 */
	public function is_available();

	/**
	 * Generate an embedding vector for a single text input.
	 *
	 * @param string $text Text to embed.
	 * @return array<int,float>|WP_Error Vector on success, WP_Error on failure.
	 */
	public function embed( $text );
}
