/** @jsxImportSource react */
import '@testing-library/jest-dom/vitest';

/**
 * Provide a minimal `NVOOS_COMIC_READER` global for tests, mirroring the
 * English localization object injected by the WordPress shortcode.
 */
beforeAll(() => {
	(window as unknown as { NVOOS_COMIC_READER: unknown }).NVOOS_COMIC_READER = {
		apiUrl: 'http://example.test/wp-json/nvoos-comic-reader/v1',
		nonce: 'test-nonce',
		config: { comicId: 0, mode: 'library', height: '', direction: 'ltr' },
		i18n: {
			loading: 'Loading comic…',
			noComics: 'No comics found in your library.',
			dropHint: 'Drop CBR/CBZ files here or click to upload',
			pageOf: 'Page %1$d of %2$d',
			zoomIn: 'Zoom in',
			zoomOut: 'Zoom out',
			fitWidth: 'Fit width',
			fitHeight: 'Fit height',
			fitScreen: 'Fit to screen',
			fullscreen: 'Fullscreen',
			exitFullscreen: 'Exit fullscreen',
			previousPage: 'Previous page',
			nextPage: 'Next page',
			library: 'Library',
			deleteComic: 'Delete comic',
			confirmDelete: 'Are you sure you want to delete this comic?',
			uploading: 'Uploading…',
			extracting: 'Extracting pages…',
			errorLoad: 'Failed to load comic.',
			unsupported: 'Unsupported file format.',
			singlePage: 'Single page',
			doublePage: 'Double page',
			readingLtr: 'Left-to-right',
			readingRtl: 'Right-to-left',
			retry: 'Retry',
			cancel: 'Cancel',
			noPages: 'No pages to display.',
			pageAlt: 'Page %1$d',
			settings: 'Reader settings',
			close: 'Close',
			help: 'Keyboard shortcuts',
			thumbnails: 'Pages overview',
			readingMode: 'Reading mode',
			modePaged: 'Paged',
			modeScroll: 'Vertical scroll',
			modeWebtoon: 'Webtoon',
			scaleType: 'Scale',
			original: 'Original size',
			background: 'Background',
			backgroundWhite: 'White',
			backgroundGray: 'Gray',
			backgroundBlack: 'Black',
			transitions: 'Page transition',
			transitionNone: 'None',
			transitionFade: 'Fade',
			transitionSlide: 'Slide',
			gestures: 'Touch gestures',
			gesturesOn: 'Enabled',
			gesturesOff: 'Disabled',
			continueReading: 'Continue reading',
			allComics: 'All comics',
			searchPlaceholder: 'Search comics…',
			sortLabel: 'Sort',
			sortDate: 'Newest first',
			sortTitle: 'Title A–Z',
			sortSize: 'Largest first',
			filterSeries: 'Series',
			allSeries: 'All series',
			noSeries: 'No series',
			readPercent: '%1$d%% read',
			completedLabel: 'Completed',
			pageProgress: 'Page %1$d',
		},
	};
});
