<?php
/**
 * Shared helpers for proxying REST requests through WordPress.
 *
 * @package WP_MCP_AI
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Provide utilities for building REST URLs that respect trusted proxy headers.
 */
class WP_MCP_AI_Proxy_Utils {

	/**
	 * Build a REST URL for the provided namespace and route, applying any
	 * trusted proxy host overrides when the site itself is bound to an
	 * internal or loopback interface.
	 *
	 * @param string $namespace REST namespace (for example `jet-engine/v2`).
	 * @param string $route     REST route relative to the namespace.
	 *
	 * @return string
	 */
	public static function build_rest_url( $namespace, $route ) {
		$namespace = trim( (string) $namespace, '/' );
		$route     = ltrim( (string) $route, '/' );

		$path = $namespace;
		if ( '' !== $route ) {
			$path .= '/' . $route;
		}

		$path = ltrim( $path, '/' );

		$url = rest_url( $path );

		return self::maybe_override_host( $url );
	}

	/**
	 * Apply a trusted proxy host override when appropriate.
	 *
	 * @param string $url Base REST URL generated by WordPress.
	 *
	 * @return string
	 */
	protected static function maybe_override_host( $url ) {
		if ( ! is_string( $url ) || '' === $url ) {
			return $url;
		}

		$parts = wp_parse_url( $url );
		if ( ! is_array( $parts ) || empty( $parts['host'] ) ) {
			return $url;
		}

		$original_host = strtolower( (string) $parts['host'] );

		if ( ! self::is_internal_host( $original_host ) ) {
			return $url;
		}

		$forwarded = self::extract_forwarded_host();
		if ( null === $forwarded ) {
			return $url;
		}

		if ( ! self::is_trusted_proxy_request() ) {
			return $url;
		}

		if ( ! self::is_forwarded_host_allowed( $forwarded['host'] ) ) {
			return $url;
		}

		$parts['host'] = $forwarded['host'];

		if ( isset( $forwarded['port'] ) ) {
			$parts['port'] = $forwarded['port'];
		} else {
			unset( $parts['port'] );
		}

		return self::unparse_url( $parts );
	}

	/**
	 * Determine whether the supplied host represents an internal, loopback, or
	 * otherwise non-public interface.
	 *
	 * @param string $host Hostname or IP address.
	 *
	 * @return bool
	 */
	protected static function is_internal_host( $host ) {
		$host = self::normalise_host( $host );

		if ( '' === $host ) {
			return false;
		}

		if ( 'localhost' === $host ) {
			return true;
		}

		if ( filter_var( $host, FILTER_VALIDATE_IP ) ) {
			return ! filter_var( $host, FILTER_VALIDATE_IP, FILTER_FLAG_NO_PRIV_RANGE | FILTER_FLAG_NO_RES_RANGE );
		}

		return false;
	}

	/**
	 * Extract and validate the forwarded host header when present.
	 *
	 * @return array|null Array with `host` and optional `port` keys or null when unavailable.
	 */
	protected static function extract_forwarded_host() {
		if ( empty( $_SERVER['HTTP_X_FORWARDED_HOST'] ) ) { // phpcs:ignore WordPress.Security.ValidatedSanitizedInput.InputNotSanitized
			return null;
		}

		$raw = (string) wp_unslash( $_SERVER['HTTP_X_FORWARDED_HOST'] ); // phpcs:ignore WordPress.Security.ValidatedSanitizedInput.InputNotSanitized

		if ( false !== strpos( $raw, ',' ) ) {
			$raw = explode( ',', $raw );
			$raw = reset( $raw );
		}

		$raw = trim( $raw );
		if ( '' === $raw ) {
			return null;
		}

		$host = $raw;
		$port = null;

		if ( '[' === substr( $raw, 0, 1 ) ) {
			$ipv6_end = strpos( $raw, ']' );
			if ( false === $ipv6_end ) {
				return null;
			}

			$host = substr( $raw, 1, $ipv6_end - 1 );
			$rest = substr( $raw, $ipv6_end + 1 );

			if ( 0 === strpos( $rest, ':' ) ) {
				$port = substr( $rest, 1 );
			}
		} elseif ( false !== strpos( $raw, ':' ) ) {
			$segments = explode( ':', $raw, 2 );
			$host     = $segments[0];
			$port     = $segments[1];
		}

		$host = self::normalise_host( $host );
		if ( '' === $host || ! self::is_valid_host( $host ) ) {
			return null;
		}

		if ( null !== $port ) {
			$port = trim( $port );
			if ( '' === $port ) {
				$port = null;
			} elseif ( ! ctype_digit( $port ) ) {
				return null;
			} else {
				$port = (int) $port;
				if ( $port < 1 || $port > 65535 ) {
					return null;
				}
			}
		}

		$result = array(
			'host' => $host,
		);

		if ( null !== $port ) {
			$result['port'] = $port;
		}

		return $result;
	}

	/**
	 * Determine if the forwarded host should be trusted for this request.
	 *
	 * @return bool
	 */
	protected static function is_trusted_proxy_request() {
		$remote_addr = '';

		if ( isset( $_SERVER['REMOTE_ADDR'] ) ) { // phpcs:ignore WordPress.Security.ValidatedSanitizedInput.InputNotSanitized
			$remote_addr = sanitize_text_field( wp_unslash( $_SERVER['REMOTE_ADDR'] ) ); // phpcs:ignore WordPress.Security.ValidatedSanitizedInput.InputNotSanitized
		}

		$remote_addr = trim( $remote_addr );

		$trusted = apply_filters( 'wp_mcp_ai_trusted_proxy_addresses', array(), $remote_addr );
		if ( is_array( $trusted ) && in_array( $remote_addr, $trusted, true ) ) {
			return true;
		}

		if ( '' === $remote_addr ) {
			return false;
		}

		if ( filter_var( $remote_addr, FILTER_VALIDATE_IP ) ) {
			$is_private = ! filter_var( $remote_addr, FILTER_VALIDATE_IP, FILTER_FLAG_NO_PRIV_RANGE | FILTER_FLAG_NO_RES_RANGE );
			if ( $is_private ) {
				return true;
			}
		}

		/**
		 * Allow integrations to trust additional proxy addresses.
		 *
		 * @param bool   $trusted     Whether the forwarded host should be trusted.
		 * @param string $remote_addr Remote address observed by PHP.
		 */
		return (bool) apply_filters( 'wp_mcp_ai_trust_forwarded_host_request', false, $remote_addr );
	}

	/**
	 * Confirm the forwarded host is present in the allow list.
	 *
	 * @param string $host Forwarded host.
	 *
	 * @return bool
	 */
	protected static function is_forwarded_host_allowed( $host ) {
		$host = self::normalise_host( $host );
		if ( '' === $host ) {
			return false;
		}

		$allowed = array();

		if ( isset( $_SERVER['HTTP_HOST'] ) ) { // phpcs:ignore WordPress.Security.ValidatedSanitizedInput.InputNotSanitized
			$request_host = sanitize_text_field( wp_unslash( $_SERVER['HTTP_HOST'] ) ); // phpcs:ignore WordPress.Security.ValidatedSanitizedInput.InputNotSanitized
			$request_host = self::normalise_host( explode( ':', $request_host, 2 )[0] );

			if ( '' !== $request_host ) {
				$allowed[] = $request_host;
			}
		}

		$home_host = wp_parse_url( home_url(), PHP_URL_HOST );
		if ( ! empty( $home_host ) ) {
			$allowed[] = self::normalise_host( $home_host );
		}

		$allowed = array_filter( array_unique( $allowed ) );

		/**
		 * Filter the allow list of forwarded hosts that may be trusted for proxy requests.
		 *
		 * @param string[] $allowed Allow list of hosts.
		 * @param string   $host    Candidate forwarded host.
		 */
		$allowed = apply_filters( 'wp_mcp_ai_trusted_forwarded_hosts', $allowed, $host );

		if ( ! is_array( $allowed ) ) {
			return false;
		}

		$allowed = array_map( array( __CLASS__, 'normalise_host' ), $allowed );
		$allowed = array_filter( array_unique( $allowed ) );

		return in_array( $host, $allowed, true );
	}

	/**
	 * Normalise host strings for comparison.
	 *
	 * @param string $host Host string.
	 *
	 * @return string
	 */
	protected static function normalise_host( $host ) {
		$host = strtolower( trim( (string) $host ) );

		if ( '' === $host ) {
			return '';
		}

		$host = trim( $host, '[]' );

		return $host;
	}

	/**
	 * Determine whether a host value is syntactically valid.
	 *
	 * @param string $host Host string.
	 *
	 * @return bool
	 */
	protected static function is_valid_host( $host ) {
		if ( filter_var( $host, FILTER_VALIDATE_IP ) ) {
			return true;
		}

		$parsed = wp_parse_url( 'http://' . $host );

		return is_array( $parsed ) && ! empty( $parsed['host'] );
	}

	/**
	 * Reconstruct a URL from its parse_url components.
	 *
	 * @param array $parts Parsed URL components.
	 *
	 * @return string
	 */
	protected static function unparse_url( array $parts ) {
		$scheme = isset( $parts['scheme'] ) ? $parts['scheme'] . '://' : '';
		$user   = isset( $parts['user'] ) ? $parts['user'] : '';
		$pass   = isset( $parts['pass'] ) ? ':' . $parts['pass'] : '';
		$auth   = '';
		if ( '' !== $user ) {
			$auth = $user . $pass . '@';
		}

		$host = isset( $parts['host'] ) ? $parts['host'] : '';
		if ( '' !== $host && filter_var( $host, FILTER_VALIDATE_IP, FILTER_FLAG_IPV6 ) ) {
			$host = '[' . $host . ']';
		}

		$port     = isset( $parts['port'] ) ? ':' . (int) $parts['port'] : '';
		$path     = isset( $parts['path'] ) ? $parts['path'] : '';
		$query    = isset( $parts['query'] ) && '' !== $parts['query'] ? '?' . $parts['query'] : '';
		$fragment = isset( $parts['fragment'] ) && '' !== $parts['fragment'] ? '#' . $parts['fragment'] : '';

		return $scheme . $auth . $host . $port . $path . $query . $fragment;
	}
}
