<?php
/**
 * AI Transparency Service
 *
 * Central controller for AI transparency compliance under EU AI Act Article 50,
 * India IT Rules 2026 (SGI), and US state laws (CA SB 942, NY S.8420).
 *
 * Coordinates:
 * - AI disclosure badge rendering in chat UI (Article 50(1))
 * - Transparency headers on REST API responses (Article 50(2))
 * - Consent modal coordination with Consent Manager
 * - Settings-based gating of all transparency features
 *
 * @package WP_MCP_AI
 * @since   1.1.45
 * @author    NV Digital Solutions
 * @copyright Copyright (c) 2025-2026 NV Digital Solutions
 * @license   GPL-3.0-or-later
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * AI Transparency Service class.
 *
 * Singleton that provides disclosure rendering, header injection,
 * and coordination between consent and provenance subsystems.
 */
class WP_MCP_AI_Transparency_Service {

	/**
	 * Singleton instance.
	 *
	 * @var WP_MCP_AI_Transparency_Service|null
	 */
	private static $instance = null;

	/**
	 * Cached settings array.
	 *
	 * @var array|null
	 */
	private $settings = null;

	/**
	 * Default AI disclosure message when no custom message is configured.
	 *
	 * @var string
	 */
	const DEFAULT_DISCLOSURE_MESSAGE = 'You are interacting with an AI assistant. Responses may be generated by artificial intelligence and should be reviewed for accuracy.';

	/**
	 * Default consent message when no custom message is configured.
	 *
	 * @var string
	 */
	const DEFAULT_CONSENT_MESSAGE = 'This chat is powered by AI. Your messages may be processed by AI models to generate responses. By continuing, you acknowledge and consent to AI-powered interactions.';

	/**
	 * ARIA label for the AI disclosure banner.
	 *
	 * @var string
	 */
	const DISCLOSURE_ARIA_LABEL = 'AI Assistant Notice';

	/**
	 * CSS class prefix used by all transparency UI elements.
	 *
	 * @var string
	 */
	const CSS_PREFIX = 'wp-mcp-ai-transparency';

	/**
	 * Get singleton instance.
	 *
	 * @return WP_MCP_AI_Transparency_Service
	 */
	public static function get_instance() {
		if ( null === self::$instance ) {
			self::$instance = new self();
		}
		return self::$instance;
	}

	/**
	 * Constructor — registers hooks.
	 */
	private function __construct() {
		add_action( 'init', array( $this, 'register_assets' ) );
		add_action( 'wp_enqueue_scripts', array( $this, 'enqueue_assets' ) );
	}

	/**
	 * Boot the transparency service.
	 *
	 * Called from the loader after all transparency classes are available.
	 * Registers REST header injection and consent endpoint hooks.
	 *
	 * @since 1.1.45
	 * @return void
	 */
	public static function boot() {
		$instance = self::get_instance();

		// Register REST response header injection.
		add_filter( 'rest_post_dispatch', array( $instance, 'add_disclosure_headers' ), 10, 3 );

		// Register consent REST endpoint if Consent Manager is available.
		if ( class_exists( 'WP_MCP_AI_Consent_Manager' ) ) {
			add_action( 'rest_api_init', array( 'WP_MCP_AI_Consent_Manager', 'register_consent_endpoint' ) );
		}

		// Hook provenance logging into transcript recording.
		if ( class_exists( 'WP_MCP_AI_Generation_Provenance' ) ) {
			add_action( 'wp_mcp_ai_chat_transcript_recorded', array( 'WP_MCP_AI_Generation_Provenance', 'on_transcript_recorded' ), 10, 7 );
		}
	}

	/**
	 * Register transparency CSS assets.
	 *
	 * @since 1.1.45
	 * @return void
	 */
	public function register_assets() {
		$css_file = 'assets/css/chat-transparency.css';
		$css_path = WP_MCP_AI_PATH . $css_file;
		$css_url  = WP_MCP_AI_URL . $css_file;
		$version  = file_exists( $css_path ) ? filemtime( $css_path ) : WP_MCP_AI_VERSION;

		wp_register_style(
			'wp-mcp-ai-transparency',
			$css_url,
			array( 'wp-mcp-ai-chat' ),
			$version
		);
	}

	/**
	 * Enqueue transparency assets when chat is present on the page.
	 *
	 * @since 1.1.45
	 * @return void
	 */
	public function enqueue_assets() {
		if ( ! $this->is_transparency_enabled() ) {
			return;
		}

		wp_enqueue_style( 'wp-mcp-ai-transparency' );
	}

	/**
	 * Check if AI disclosure is enabled in settings.
	 *
	 * @since 1.1.45
	 * @return bool
	 */
	public function is_transparency_enabled() {
		$settings = $this->get_settings();
		return ! empty( $settings['enable_ai_disclosure'] );
	}

	/**
	 * Check if consent modal is required.
	 *
	 * @since 1.1.45
	 * @return bool
	 */
	public function is_consent_required() {
		$settings = $this->get_settings();
		return ! empty( $settings['enable_consent_modal'] );
	}

	/**
	 * Check if transparency headers are enabled.
	 *
	 * @since 1.1.45
	 * @return bool
	 */
	public function is_headers_enabled() {
		$settings = $this->get_settings();
		return ! empty( $settings['enable_transparency_headers'] );
	}

	/**
	 * Check if generation provenance logging is enabled.
	 *
	 * @since 1.1.45
	 * @return bool
	 */
	public function is_provenance_enabled() {
		$settings = $this->get_settings();
		return ! empty( $settings['enable_generation_logging'] );
	}

	/**
	 * Get the configured disclosure message or default.
	 *
	 * @since 1.1.45
	 * @return string
	 */
	public function get_disclosure_message() {
		$settings = $this->get_settings();
		$message  = isset( $settings['ai_disclosure_message'] ) ? trim( $settings['ai_disclosure_message'] ) : '';

		if ( '' === $message ) {
			$message = self::DEFAULT_DISCLOSURE_MESSAGE;
		}

		/**
		 * Filter the AI disclosure message displayed to users.
		 *
		 * @since 1.1.45
		 *
		 * @param string $message The disclosure message text.
		 */
		return apply_filters( 'wp_mcp_ai_disclosure_message', $message );
	}

	/**
	 * Get the configured consent message or default.
	 *
	 * @since 1.1.45
	 * @return string
	 */
	public function get_consent_message() {
		$settings = $this->get_settings();
		$message  = isset( $settings['consent_message'] ) ? trim( $settings['consent_message'] ) : '';

		if ( '' === $message ) {
			$message = self::DEFAULT_CONSENT_MESSAGE;
		}

		/**
		 * Filter the AI consent message displayed to users.
		 *
		 * @since 1.1.45
		 *
		 * @param string $message The consent message text.
		 */
		return apply_filters( 'wp_mcp_ai_consent_message', $message );
	}

	/**
	 * Get the disclosure position setting.
	 *
	 * @since 1.1.45
	 * @return string 'banner', 'header', or 'both'
	 */
	public function get_disclosure_position() {
		$settings = $this->get_settings();
		$position = isset( $settings['ai_disclosure_position'] ) ? $settings['ai_disclosure_position'] : 'banner';

		if ( ! in_array( $position, array( 'banner', 'header', 'both' ), true ) ) {
			$position = 'banner';
		}

		return $position;
	}

	/**
	 * Get generation log retention period in days.
	 *
	 * @since 1.1.45
	 * @return int
	 */
	public function get_log_retention_days() {
		$settings = $this->get_settings();
		$days     = isset( $settings['generation_log_retention_days'] ) ? absint( $settings['generation_log_retention_days'] ) : 365;

		return max( 1, $days );
	}

	/**
	 * Load and cache plugin settings.
	 *
	 * @since 1.1.45
	 * @return array
	 */
	private function get_settings() {
		if ( null === $this->settings ) {
			if ( class_exists( 'WP_MCP_AI_Admin_Settings_Base' ) ) {
				$this->settings = WP_MCP_AI_Admin_Settings_Base::get_settings();
			} else {
				$this->settings = get_option( 'wp_mcp_ai_settings', array() );
			}
		}

		return $this->settings;
	}

	/**
	 * Add AI transparency headers to REST API responses.
	 *
	 * Hooks into rest_post_dispatch to inject X-AI-Generated, X-AI-Provider,
	 * and X-AI-Model headers on chat endpoint responses.
	 *
	 * @since 1.1.45
	 *
	 * @param WP_REST_Response $response  The REST response object.
	 * @param WP_REST_Server   $server    The REST server instance.
	 * @param WP_REST_Request  $request   The REST request instance.
	 * @return WP_REST_Response Modified response.
	 */
	public function add_disclosure_headers( $response, $server, $request ) {
		if ( ! $this->is_headers_enabled() ) {
			return $response;
		}

		if ( ! $response instanceof WP_REST_Response && ! $response instanceof WP_HTTP_Response ) {
			return $response;
		}

		$route = $request->get_route();
		$route = untrailingslashit( $route );

		// Only tag chat-related endpoints.
		$chat_routes = array(
			'/mcp-ai/v1/chat',
			'/mcp-ai/v1/chat-client',
			'/mcp-ai/v1/sse',
		);

		$is_chat_route = false;
		foreach ( $chat_routes as $chat_route ) {
			if ( 0 === strpos( $route, $chat_route ) ) {
				$is_chat_route = true;
				break;
			}
		}

		if ( ! $is_chat_route ) {
			return $response;
		}

		// Extract model and provider info from request context when available.
		$model    = '';
		$provider = '';

		if ( $request instanceof WP_REST_Request ) {
			$model = $request->get_param( 'model' );
			if ( ! is_string( $model ) ) {
				$model = '';
			}
			$provider = $request->get_param( 'provider' );
			if ( ! is_string( $provider ) ) {
				$provider = '';
			}
		}

		// Set transparency headers.
		$headers                      = $response->get_headers();
		$headers['X-AI-Generated']    = 'true';
		$headers['X-AI-Transparency'] = 'https://artificialintelligenceact.eu/transparency-rules-article-50/';

		if ( '' !== $model ) {
			$headers['X-AI-Model'] = sanitize_text_field( $model );
		}

		if ( '' !== $provider ) {
			$headers['X-AI-Provider'] = sanitize_text_field( $provider );
		}

		$response->set_headers( $headers );

		return $response;
	}

	/**
	 * Render the AI disclosure banner HTML.
	 *
	 * Produces an ARIA-accessible banner that informs users they are
	 * interacting with an AI assistant, per EU AI Act Article 50(1).
	 *
	 * @since 1.1.45
	 *
	 * @param string $position Optional position override. Accepts 'banner', 'header', or '' for default.
	 * @return string HTML markup for the disclosure banner.
	 */
	public function get_disclosure_banner_html( $position = '' ) {
		if ( ! $this->is_transparency_enabled() ) {
			return '';
		}

		if ( '' === $position ) {
			$position = $this->get_disclosure_position();
		}

		$message = $this->get_disclosure_message();
		$output  = '';

		if ( in_array( $position, array( 'banner', 'both' ), true ) ) {
			$output .= sprintf(
				'<div class="%1$s-banner" role="status" aria-label="%2$s">' .
				'<span class="%1$s-badge" aria-hidden="true">%3$s</span>' .
				'<span class="%1$s-message">%4$s</span>' .
				'</div>',
				esc_attr( self::CSS_PREFIX ),
				esc_attr( self::DISCLOSURE_ARIA_LABEL ),
				esc_html__( 'AI', 'mcp-ai-wpoos' ),
				esc_html( $message )
			);
		}

		if ( in_array( $position, array( 'header', 'both' ), true ) ) {
			$output .= sprintf(
				'<div class="%1$s-header-badge" role="status" aria-label="%2$s">' .
				'<span class="%1$s-small-badge">%3$s</span>' .
				'</div>',
				esc_attr( self::CSS_PREFIX ),
				esc_attr( self::DISCLOSURE_ARIA_LABEL ),
				esc_html__( 'AI Assistant', 'mcp-ai-wpoos' )
			);
		}

		return $output;
	}

	/**
	 * Render the consent modal HTML.
	 *
	 * Produces an accessible modal dialog that requests user consent
	 * before the first AI interaction, per EU AI Act Article 50(1).
	 *
	 * @since 1.1.45
	 *
	 * @return string HTML markup for the consent modal, or empty string if consent is not required.
	 */
	public function get_consent_modal_html() {
		if ( ! $this->is_consent_required() ) {
			return '';
		}

		$message       = $this->get_consent_message();
		$agree_label   = __( 'I Understand', 'mcp-ai-wpoos' );
		$decline_label = __( 'Decline', 'mcp-ai-wpoos' );
		$modal_title   = __( 'AI Assistant Notice', 'mcp-ai-wpoos' );
		$prefix        = self::CSS_PREFIX;

		$output = sprintf(
			'<div class="%1$s-consent-overlay" id="%1$s-consent-overlay" role="dialog" aria-modal="true" aria-labelledby="%1$s-consent-title" style="display:none;">' .
			'<div class="%1$s-consent-modal">' .
			'<h3 class="%1$s-consent-title" id="%1$s-consent-title">%2$s</h3>' .
			'<div class="%1$s-consent-body">' .
			'<p>%3$s</p>' .
			'</div>' .
			'<div class="%1$s-consent-actions">' .
			'<button type="button" class="%1$s-consent-decline" aria-label="%5$s">%5$s</button>' .
			'<button type="button" class="%1$s-consent-agree" aria-label="%4$s">%4$s</button>' .
			'</div>' .
			'</div>' .
			'</div>',
			esc_attr( $prefix ),
			esc_html( $modal_title ),
			esc_html( $message ),
			esc_html( $agree_label ),
			esc_html( $decline_label )
		);

		return $output;
	}

	/**
	 * Get the data attributes for the chat container to signal transparency features to JS.
	 *
	 * @since 1.1.45
	 *
	 * @return array Associative array of data attributes and their values.
	 */
	public function get_chat_data_attributes() {
		$attrs = array();

		if ( $this->is_transparency_enabled() ) {
			$attrs['data-ai-disclosure']          = 'true';
			$attrs['data-ai-disclosure-position'] = $this->get_disclosure_position();
		}

		if ( $this->is_consent_required() ) {
			$attrs['data-ai-consent'] = 'true';
		}

		return $attrs;
	}

	/**
	 * Prevent cloning of the singleton.
	 */
	private function __clone() {}

	/**
	 * Prevent unserializing of the singleton.
	 *
	 * @since 1.1.45
	 *
	 * @return void
	 * @throws \Exception Always.
	 */
	public function __wakeup() {
		throw new \Exception( 'Cannot unserialize singleton' );
	}
}
