<?php
/**
 * Helpers for aligning REST URLs with the active request context.
 *
 *
 * @package WP_MCP_AI
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Utilities for reconciling WordPress REST URLs with the inbound request.
 */
class WP_MCP_AI_Request_Context {
	/**
	 * Normalise a REST URL so loopback hosts match the current request host.
	 *
	 * @param string $url Absolute REST URL generated by rest_url().
	 * @return string Normalised URL using the current request host when possible.
	 */
	public static function normalise_rest_url( $url ) {
		if ( ! is_string( $url ) || '' === $url ) {
			return $url;
		}

		$parts = wp_parse_url( $url );
		if ( empty( $parts ) || empty( $parts['host'] ) ) {
			return $url;
		}

		if ( ! self::is_loopback_host( $parts['host'] ) ) {
			return $url;
		}

		$request_host = self::get_current_request_host();
		if ( empty( $request_host ) || empty( $request_host['host'] ) ) {
			return $url;
		}

		$parts['host'] = $request_host['host'];

		if ( isset( $request_host['port'] ) && null !== $request_host['port'] ) {
			$parts['port'] = $request_host['port'];
		} else {
			unset( $parts['port'] );
		}

		$parts['scheme'] = self::determine_request_scheme( $parts );

		$normalised = self::build_url_from_parts( $parts );

		/**
		 * Filter the normalised REST URL before returning it.
		 *
		 * @param string $normalised Normalised REST URL.
		 * @param string $url        Original URL provided to the helper.
		 */
		return apply_filters( 'wp_mcp_ai_normalised_rest_url', $normalised, $url );
	}

	/**
	 * Determine whether a host refers to a loopback address.
	 *
	 * @param string $host Host portion of a URL.
	 * @return bool
	 */
	protected static function is_loopback_host( $host ) {
		$host = strtolower( trim( (string) $host ) );

		if ( '' === $host ) {
			return false;
		}

		if ( 'localhost' === $host || '[::1]' === $host ) {
			return true;
		}

		if ( filter_var( $host, FILTER_VALIDATE_IP, FILTER_FLAG_IPV6 ) ) {
			return in_array( $host, array( '::1', '0:0:0:0:0:0:0:1' ), true );
		}

		if ( filter_var( $host, FILTER_VALIDATE_IP, FILTER_FLAG_IPV4 ) ) {
			return 0 === strpos( $host, '127.' );
		}

		return false;
	}

	/**
	 * Retrieve the current request host for proxying external REST requests.
	 *
	 * @return array|null Array with `host` and optional `port` or null when unavailable.
	 */
	protected static function get_current_request_host() {
		$host_header = '';

		if ( ! empty( $_SERVER['HTTP_X_FORWARDED_HOST'] ) ) {
			$forwarded_raw   = sanitize_text_field( wp_unslash( $_SERVER['HTTP_X_FORWARDED_HOST'] ) );
			$forwarded_hosts = explode( ',', $forwarded_raw );
			$host_header     = trim( reset( $forwarded_hosts ) );
		}

		if ( '' === $host_header && ! empty( $_SERVER['HTTP_HOST'] ) ) {
			$host_header = trim( sanitize_text_field( wp_unslash( $_SERVER['HTTP_HOST'] ) ) );
		}

		if ( '' === $host_header && ! empty( $_SERVER['SERVER_NAME'] ) ) {
			$host_header = trim( sanitize_text_field( wp_unslash( $_SERVER['SERVER_NAME'] ) ) );
		}

		if ( '' === $host_header ) {
			return null;
		}

		$host_header = preg_replace( '#\s+#', '', $host_header );
		if ( '' === $host_header ) {
			return null;
		}

		$parsed = wp_parse_url( 'http://' . $host_header );
		if ( empty( $parsed ) || empty( $parsed['host'] ) ) {
			return null;
		}

		$result = array(
			'host' => strtolower( $parsed['host'] ),
		);

		if ( isset( $parsed['port'] ) ) {
			$result['port'] = absint( $parsed['port'] );
		}

		return $result;
	}

	/**
	 * Determine the best-fit scheme for proxied REST requests.
	 *
	 * @param array $parts Parsed REST URL parts.
	 * @return string
	 */
	protected static function determine_request_scheme( array $parts ) {
		$scheme = '';

		if ( ! empty( $_SERVER['HTTP_X_FORWARDED_PROTO'] ) ) {
			$forwarded_proto  = sanitize_text_field( wp_unslash( $_SERVER['HTTP_X_FORWARDED_PROTO'] ) );
			$proto_candidates = explode( ',', $forwarded_proto );
			$proto            = strtolower( trim( reset( $proto_candidates ) ) );

			if ( in_array( $proto, array( 'http', 'https' ), true ) ) {
				$scheme = $proto;
			}
		}

		if ( '' === $scheme && ! empty( $_SERVER['REQUEST_SCHEME'] ) ) {
			$candidate = strtolower( trim( sanitize_text_field( wp_unslash( $_SERVER['REQUEST_SCHEME'] ) ) ) );

			if ( in_array( $candidate, array( 'http', 'https' ), true ) ) {
				$scheme = $candidate;
			}
		}

		if ( '' === $scheme && function_exists( 'is_ssl' ) && is_ssl() ) {
			$scheme = 'https';
		}

		if ( '' === $scheme && isset( $_SERVER['SERVER_PORT'] ) ) {
			$port = absint( $_SERVER['SERVER_PORT'] );

			if ( 443 === $port ) {
				$scheme = 'https';
			} elseif ( 80 === $port ) {
				$scheme = 'http';
			}
		}

		if ( '' === $scheme && isset( $parts['scheme'] ) && '' !== $parts['scheme'] ) {
			$scheme = $parts['scheme'];
		}

		if ( '' === $scheme ) {
			$scheme = 'http';
		}

		return $scheme;
	}

	/**
	 * Assemble a URL string from parsed components.
	 *
	 * @param array $parts Parsed URL components.
	 * @return string
	 */
	protected static function build_url_from_parts( array $parts ) {
		$scheme = isset( $parts['scheme'] ) && '' !== $parts['scheme'] ? $parts['scheme'] . '://' : '';
		$host   = isset( $parts['host'] ) ? $parts['host'] : '';

		if ( '' !== $host && filter_var( $host, FILTER_VALIDATE_IP, FILTER_FLAG_IPV6 ) ) {
			$host = '[' . $host . ']';
		}

		$port = '';
		if ( isset( $parts['port'] ) && $parts['port'] ) {
			$port = ':' . absint( $parts['port'] );
		}

		$path = isset( $parts['path'] ) ? $parts['path'] : '';

		$query = '';
		if ( isset( $parts['query'] ) && '' !== $parts['query'] ) {
			$query = '?' . $parts['query'];
		}

		$fragment = '';
		if ( isset( $parts['fragment'] ) && '' !== $parts['fragment'] ) {
			$fragment = '#' . $parts['fragment'];
		}

		return $scheme . $host . $port . $path . $query . $fragment;
	}
}
